// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AdminUserSignIn.
const (
	AdminUserSignInOidc     AdminUserSignIn = "oidc"
	AdminUserSignInPassword AdminUserSignIn = "password"
)

// Valid indicates whether the value is a known member of the AdminUserSignIn enum.
func (e AdminUserSignIn) Valid() bool {
	switch e {
	case AdminUserSignInOidc:
		return true
	case AdminUserSignInPassword:
		return true
	default:
		return false
	}
}

// Defines values for CreateUserRequestSignIn.
const (
	CreateUserRequestSignInOidc     CreateUserRequestSignIn = "oidc"
	CreateUserRequestSignInPassword CreateUserRequestSignIn = "password"
)

// Valid indicates whether the value is a known member of the CreateUserRequestSignIn enum.
func (e CreateUserRequestSignIn) Valid() bool {
	switch e {
	case CreateUserRequestSignInOidc:
		return true
	case CreateUserRequestSignInPassword:
		return true
	default:
		return false
	}
}

// Defines values for Kind.
const (
	Human   Kind = "human"
	Service Kind = "service"
)

// Valid indicates whether the value is a known member of the Kind enum.
func (e Kind) Valid() bool {
	switch e {
	case Human:
		return true
	case Service:
		return true
	default:
		return false
	}
}

// Defines values for PolicySource.
const (
	Idp   PolicySource = "idp"
	Local PolicySource = "local"
)

// Valid indicates whether the value is a known member of the PolicySource enum.
func (e PolicySource) Valid() bool {
	switch e {
	case Idp:
		return true
	case Local:
		return true
	default:
		return false
	}
}

// Defines values for PriceEntrySource.
const (
	PriceEntrySourceCatalog PriceEntrySource = "catalog"
	PriceEntrySourceManual  PriceEntrySource = "manual"
)

// Valid indicates whether the value is a known member of the PriceEntrySource enum.
func (e PriceEntrySource) Valid() bool {
	switch e {
	case PriceEntrySourceCatalog:
		return true
	case PriceEntrySourceManual:
		return true
	default:
		return false
	}
}

// Defines values for ProviderLoginStartRequestProvider.
const (
	Chatgpt ProviderLoginStartRequestProvider = "chatgpt"
	Claude  ProviderLoginStartRequestProvider = "claude"
)

// Valid indicates whether the value is a known member of the ProviderLoginStartRequestProvider enum.
func (e ProviderLoginStartRequestProvider) Valid() bool {
	switch e {
	case Chatgpt:
		return true
	case Claude:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Admin Role = "admin"
	User  Role = "user"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Admin:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for Status.
const (
	Active  Status = "active"
	Blocked Status = "blocked"
)

// Valid indicates whether the value is a known member of the Status enum.
func (e Status) Valid() bool {
	switch e {
	case Active:
		return true
	case Blocked:
		return true
	default:
		return false
	}
}

// Defines values for UsageBucket.
const (
	Day  UsageBucket = "day"
	Hour UsageBucket = "hour"
)

// Valid indicates whether the value is a known member of the UsageBucket enum.
func (e UsageBucket) Valid() bool {
	switch e {
	case Day:
		return true
	case Hour:
		return true
	default:
		return false
	}
}

// Activity defines model for Activity.
type Activity struct {
	Audit []struct {
		// Action Examples: token.issue, token.revoke, user.policy.update, auth.sign_in
		Action  string                  `json:"action"`
		ActorId *openapi_types.UUID     `json:"actorId,omitempty"`
		At      time.Time               `json:"at"`
		Detail  *map[string]interface{} `json:"detail,omitempty"`
		Target  *string                 `json:"target,omitempty"`
	} `json:"audit"`
	Requests []struct {
		At time.Time `json:"at"`

		// CostUSD The request's estimated cost, as in CostSummary.totalUSD; null when none of its tokens had a price.
		CostUSD     *float64            `json:"costUSD,omitempty"`
		LatencyMs   int                 `json:"latencyMs"`
		Model       string              `json:"model"`
		Provider    string              `json:"provider"`
		StatusCode  int                 `json:"statusCode"`
		Stream      bool                `json:"stream"`
		TokenId     *openapi_types.UUID `json:"tokenId,omitempty"`
		TokensTotal int                 `json:"tokensTotal"`
	} `json:"requests"`
}

// AdminUser defines model for AdminUser.
type AdminUser struct {
	CreatedAt   time.Time          `json:"createdAt"`
	DisplayName string             `json:"displayName"`
	Email       *string            `json:"email,omitempty"`
	Id          openapi_types.UUID `json:"id"`

	// InvitationExpiresAt Set while an identity-provider invitation exists and no identity is linked yet; it may lie in the past (lapsed - renew it with POST .../invitation).
	InvitationExpiresAt *time.Time `json:"invitationExpiresAt,omitempty"`
	Kind                Kind       `json:"kind"`
	LastSeenAt          *time.Time `json:"lastSeenAt,omitempty"`
	MustChangePassword  bool       `json:"mustChangePassword"`

	// Policy Allow-list rules `<provider>:<model-glob>`. The glob dialect is exactly `*` (any run of characters, including `/` and `:`) and `?` (one character); everything else is literal. A wildcard covers models published later.
	Policy Policy `json:"policy"`

	// PolicySource `idp` means the policy is recomputed from group claims at every sign-in and is read-only here.
	PolicySource PolicySource `json:"policySource"`
	Role         Role         `json:"role"`

	// SignIn Sign-in methods that work now: `password` when a usable (unexpired) password is set, `oidc` when an identity-provider identity is linked. Empty for a service account and for a person whose only way in is a pending invitation.
	SignIn []AdminUserSignIn `json:"signIn"`
	Status Status            `json:"status"`
}

// AdminUserSignIn defines model for AdminUser.SignIn.
type AdminUserSignIn string

// AuthConfig defines model for AuthConfig.
type AuthConfig struct {
	// LocalLogin Whether the email-and-password form is offered.
	LocalLogin bool `json:"localLogin"`
	Oidc       struct {
		// DisplayName Button label, e.g. the identity provider's name.
		DisplayName *string `json:"displayName,omitempty"`
		Enabled     bool    `json:"enabled"`
	} `json:"oidc"`
}

// Catalog defines model for Catalog.
type Catalog struct {
	Providers []struct {
		Models []string `json:"models"`

		// Name The provider name as written in policy rules.
		Name string `json:"name"`
	} `json:"providers"`
}

// ConnectInfo defines model for ConnectInfo.
type ConnectInfo struct {
	// ApiBaseURL Public base URL of the proxied API, without a trailing slash.
	ApiBaseURL string `json:"apiBaseURL"`
}

// CostSummary What the tokens would have cost at the vendor's list prices, in US dollars: an estimate of work done, not a bill. Each request is priced when it is served, at the prices in force then, so a later price change does not rewrite history.
type CostSummary struct {
	// CacheReadUSD Input tokens read from the prompt cache, at the cache-read rate.
	CacheReadUSD float64 `json:"cacheReadUSD"`

	// CacheSavingsUSD The net effect of prompt caching against paying the input rate for every input token: what cache reads saved (cache-read tokens at input minus cache-read rate) less what cache writes cost extra (cache-write tokens at cache-write minus input rate). Negative when writes cost more than reads saved.
	CacheSavingsUSD float64 `json:"cacheSavingsUSD"`

	// CacheWriteUSD Input tokens written to the prompt cache, at the cache-write rate.
	CacheWriteUSD float64 `json:"cacheWriteUSD"`

	// InputUSD Input tokens not read from or written to the prompt cache, at the input rate.
	InputUSD float64 `json:"inputUSD"`

	// OutputUSD Output tokens, reasoning included, at the output rate.
	OutputUSD float64 `json:"outputUSD"`

	// TotalUSD The sum of the four parts below.
	TotalUSD float64 `json:"totalUSD"`

	// UnpricedTokens Tokens with no price when served (a model missing from the price list, or tokens the vendor did not classify). They are not in `totalUSD`, not counted as free.
	UnpricedTokens int `json:"unpricedTokens"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	DisplayName string `json:"displayName"`

	// Email Required for a human. Absent for a service account.
	Email *string `json:"email,omitempty"`
	Kind  Kind    `json:"kind"`

	// Policy Allow-list rules `<provider>:<model-glob>`. The glob dialect is exactly `*` (any run of characters, including `/` and `:`) and `?` (one character); everything else is literal. A wildcard covers models published later.
	Policy Policy `json:"policy"`
	Role   *Role  `json:"role,omitempty"`

	// SignIn For a human only. `password` issues a temporary password; `oidc` records an invitation the first sign-in with that address through the identity provider will claim. Ignored for a service account.
	SignIn *CreateUserRequestSignIn `json:"signIn,omitempty"`
}

// CreateUserRequestSignIn For a human only. `password` issues a temporary password; `oidc` records an invitation the first sign-in with that address through the identity provider will claim. Ignored for a service account.
type CreateUserRequestSignIn string

// CreatedUser defines model for CreatedUser.
type CreatedUser struct {
	TemporaryPassword *TemporaryPassword `json:"temporaryPassword,omitempty"`
	User              AdminUser          `json:"user"`
}

// Error defines model for Error.
type Error struct {
	// Code Stable machine code. The client translates this, not `message`.
	//
	// Examples: invalid_credentials
	Code string `json:"code"`

	// Field The request field the error is about, when there is one.
	Field *string `json:"field,omitempty"`

	// Message English diagnostic for logs. Not for display.
	Message string `json:"message"`
}

// IssueTokenRequest defines model for IssueTokenRequest.
type IssueTokenRequest struct {
	// Label Printable text; control characters are refused.
	Label string `json:"label"`
}

// IssuedToken defines model for IssuedToken.
type IssuedToken struct {
	// Secret The full API token. Shown once.
	Secret string `json:"secret"`
	Token  Token  `json:"token"`
}

// Kind defines model for Kind.
type Kind string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Me defines model for Me.
type Me struct {
	DisplayName string             `json:"displayName"`
	Email       *string            `json:"email,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Kind        Kind               `json:"kind"`

	// Policy Allow-list rules `<provider>:<model-glob>`. The glob dialect is exactly `*` (any run of characters, including `/` and `:`) and `?` (one character); everything else is literal. A wildcard covers models published later.
	Policy Policy `json:"policy"`

	// PolicySource `idp` means the policy is recomputed from group claims at every sign-in and is read-only here.
	PolicySource PolicySource `json:"policySource"`

	// Restricted True while a temporary password has not been changed.
	Restricted bool `json:"restricted"`
	Role       Role `json:"role"`
}

// ModelPrice US dollars per million tokens. An estimate of work done, not a bill.
type ModelPrice struct {
	CacheRead  float64 `json:"cacheRead"`
	CacheWrite float64 `json:"cacheWrite"`
	Input      float64 `json:"input"`
	Model      string  `json:"model"`
	Output     float64 `json:"output"`
	Provider   string  `json:"provider"`
}

// PasswordChangeRequest defines model for PasswordChangeRequest.
type PasswordChangeRequest struct {
	// CurrentPassword Required on a full session.
	CurrentPassword *string `json:"currentPassword,omitempty"`
	NewPassword     string  `json:"newPassword"`
}

// Policy Allow-list rules `<provider>:<model-glob>`. The glob dialect is exactly `*` (any run of characters, including `/` and `:`) and `?` (one character); everything else is literal. A wildcard covers models published later.
type Policy = []string

// PolicyPreview defines model for PolicyPreview.
type PolicyPreview struct {
	// Covered Models of today's catalogue the rules allow.
	Covered []struct {
		Model    string `json:"model"`
		Provider string `json:"provider"`
	} `json:"covered"`
	Errors []struct {
		// Code Examples: invalid_rule
		Code string `json:"code"`
		Rule string `json:"rule"`
	} `json:"errors"`
}

// PolicyPreviewRequest defines model for PolicyPreviewRequest.
type PolicyPreviewRequest struct {
	// Rules Allow-list rules `<provider>:<model-glob>`. The glob dialect is exactly `*` (any run of characters, including `/` and `:`) and `?` (one character); everything else is literal. A wildcard covers models published later.
	Rules Policy `json:"rules"`
}

// PolicySource `idp` means the policy is recomputed from group claims at every sign-in and is read-only here.
type PolicySource string

// PriceCatalog The automatically updated price catalog.
type PriceCatalog struct {
	// ChangedAt When the catalog prices in force last changed.
	ChangedAt *time.Time `json:"changedAt,omitempty"`

	// CheckedAt The last successful check, whether or not the catalog had changed.
	CheckedAt *time.Time `json:"checkedAt,omitempty"`

	// Enabled False when no catalog source is configured.
	Enabled bool `json:"enabled"`

	// LastError Why the last check failed; null once a check succeeds.
	LastError *string `json:"lastError,omitempty"`

	// Models How many catalog prices are in force.
	Models int `json:"models"`
}

// PriceEntry One price in force, in US dollars per million tokens.
type PriceEntry struct {
	CacheRead  float64 `json:"cacheRead"`
	CacheWrite float64 `json:"cacheWrite"`

	// CatalogRates For a `manual` row, the catalog's rates for the same model - what removing the override restores. Absent for a `catalog` row and when the catalog has no price.
	CatalogRates *PriceRates `json:"catalogRates,omitempty"`
	Input        float64     `json:"input"`
	Model        string      `json:"model"`
	Output       float64     `json:"output"`
	Provider     string      `json:"provider"`

	// Source `manual` is an administrator's override; it wins over the catalog.
	Source PriceEntrySource `json:"source"`

	// UpdatedAt When this row's rates last changed.
	UpdatedAt time.Time `json:"updatedAt"`
}

// PriceEntrySource `manual` is an administrator's override; it wins over the catalog.
type PriceEntrySource string

// PriceList defines model for PriceList.
type PriceList struct {
	// Catalog The automatically updated price catalog.
	Catalog PriceCatalog `json:"catalog"`

	// Prices Ordered by provider, then model.
	Prices []PriceEntry `json:"prices"`
}

// PriceRates US dollars per million tokens.
type PriceRates struct {
	CacheRead  float64 `json:"cacheRead"`
	CacheWrite float64 `json:"cacheWrite"`
	Input      float64 `json:"input"`
	Output     float64 `json:"output"`
}

// ProviderAccount defines model for ProviderAccount.
type ProviderAccount struct {
	Disabled        bool       `json:"disabled"`
	Email           *string    `json:"email,omitempty"`
	Id              string     `json:"id"`
	Label           *string    `json:"label,omitempty"`
	LastError       *string    `json:"lastError,omitempty"`
	LastRefreshedAt *time.Time `json:"lastRefreshedAt,omitempty"`

	// Provider Policy-facing provider name.
	Provider string `json:"provider"`

	// Quota Direct vendor signals. No capacity estimate.
	Quota []struct {
		ObservedAt *time.Time `json:"observedAt,omitempty"`
		ResetAt    *time.Time `json:"resetAt,omitempty"`
		UsedRatio  float32    `json:"usedRatio"`

		// Window Examples: 5h, 7d
		Window string `json:"window"`
	} `json:"quota"`

	// Status Examples: active, error, disabled
	Status string `json:"status"`
}

// ProviderLoginCompleteRequest defines model for ProviderLoginCompleteRequest.
type ProviderLoginCompleteRequest struct {
	// CallbackURL The full URL the vendor sign-in ended on.
	CallbackURL string `json:"callbackURL"`
	SessionId   string `json:"sessionId"`
}

// ProviderLoginSession defines model for ProviderLoginSession.
type ProviderLoginSession struct {
	// AuthURL Open in the administrator's own browser.
	AuthURL   string    `json:"authURL"`
	ExpiresAt time.Time `json:"expiresAt"`
	SessionId string    `json:"sessionId"`
}

// ProviderLoginStartRequest defines model for ProviderLoginStartRequest.
type ProviderLoginStartRequest struct {
	Provider ProviderLoginStartRequestProvider `json:"provider"`
}

// ProviderLoginStartRequestProvider defines model for ProviderLoginStartRequest.Provider.
type ProviderLoginStartRequestProvider string

// Role defines model for Role.
type Role string

// Settings defines model for Settings.
type Settings struct {
	// Fields The same values as typed form fields.
	Fields struct {
		// MaxRetryInterval Seconds.
		MaxRetryInterval *int    `json:"maxRetryInterval,omitempty"`
		ProxyURL         *string `json:"proxyURL,omitempty"`
		RequestRetry     *int    `json:"requestRetry,omitempty"`
	} `json:"fields"`

	// Yaml The editable part of the upstream configuration as YAML. Fields the gateway owns (listen address, auth directory, management, config API keys) are absent and cannot be set.
	Yaml string `json:"yaml"`
}

// SettingsUpdateRequest defines model for SettingsUpdateRequest.
type SettingsUpdateRequest struct {
	DryRun *bool `json:"dryRun,omitempty"`

	// Fields Patches individual typed fields. Mutually exclusive with `yaml`.
	Fields *struct {
		MaxRetryInterval *int    `json:"maxRetryInterval,omitempty"`
		ProxyURL         *string `json:"proxyURL,omitempty"`
		RequestRetry     *int    `json:"requestRetry,omitempty"`
	} `json:"fields,omitempty"`

	// Yaml Replaces the whole editable document. Mutually exclusive with `fields`.
	Yaml *string `json:"yaml,omitempty"`
}

// SettingsUpdateResult defines model for SettingsUpdateResult.
type SettingsUpdateResult struct {
	Applied bool `json:"applied"`

	// Diff Unified diff of the YAML against the running configuration.
	Diff     string   `json:"diff"`
	Settings Settings `json:"settings"`
}

// Status defines model for Status.
type Status string

// TemporaryPassword defines model for TemporaryPassword.
type TemporaryPassword struct {
	ExpiresAt time.Time `json:"expiresAt"`

	// Password Shown once.
	Password string `json:"password"`
}

// Token defines model for Token.
type Token struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Label     string             `json:"label"`

	// LastUsedAt Null if the token was never used.
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`

	// Prefix The first characters of the secret, to tell keys apart.
	Prefix    string     `json:"prefix"`
	RevokedAt *time.Time `json:"revokedAt,omitempty"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	DisplayName *string `json:"displayName,omitempty"`

	// Policy Allow-list rules `<provider>:<model-glob>`. The glob dialect is exactly `*` (any run of characters, including `/` and `:`) and `?` (one character); everything else is literal. A wildcard covers models published later.
	Policy *Policy `json:"policy,omitempty"`
	Role   *Role   `json:"role,omitempty"`
	Status *Status `json:"status,omitempty"`
}

// Usage defines model for Usage.
type Usage struct {
	Bucket UsageBucket `json:"bucket"`
	From   time.Time   `json:"from"`
	Points []struct {
		// At Start of the bucket.
		At time.Time `json:"at"`

		// CostUSD The priced part of this bucket's spend, as in `totals.cost.totalUSD`.
		CostUSD float64 `json:"costUSD"`
		Model   string  `json:"model"`

		// Requests Served requests in this bucket, as in `totals.requests`.
		Requests    int `json:"requests"`
		TokensTotal int `json:"tokensTotal"`
	} `json:"points"`
	To     time.Time `json:"to"`
	Totals struct {
		// Cost What the tokens would have cost at the vendor's list prices, in US dollars: an estimate of work done, not a bill. Each request is priced when it is served, at the prices in force then, so a later price change does not rewrite history.
		Cost CostSummary `json:"cost"`

		// Requests Served model calls. Failed attempts, including ones the gateway retried on another account, are not counted. A request that also made a side call to another model (for example an image model behind a chat request) counts once per model served.
		Requests int `json:"requests"`

		// TokensTotal Every token spent, including tokens of failed or retried attempts.
		TokensTotal int `json:"tokensTotal"`
	} `json:"totals"`
}

// UsageBucket defines model for Usage.Bucket.
type UsageBucket string

// AccountId defines model for AccountId.
type AccountId = string

// From defines model for From.
type From = time.Time

// To defines model for To.
type To = time.Time

// TokenId defines model for TokenId.
type TokenId = openapi_types.UUID

// UserId defines model for UserId.
type UserId = openapi_types.UUID

// ReplacePricesJSONBody defines parameters for ReplacePrices.
type ReplacePricesJSONBody = []ModelPrice

// UpdateProviderAccountJSONBody defines parameters for UpdateProviderAccount.
type UpdateProviderAccountJSONBody struct {
	Disabled bool `json:"disabled"`
}

// GetUserActivityParams defines parameters for GetUserActivity.
type GetUserActivityParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// OidcCallbackParams defines parameters for OidcCallback.
type OidcCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// GetMyUsageParams defines parameters for GetMyUsage.
type GetMyUsageParams struct {
	// From Defaults to 7 days before `to`.
	From *From `form:"from,omitempty" json:"from,omitempty"`

	// To Defaults to now.
	To *To `form:"to,omitempty" json:"to,omitempty"`
}

// PreviewPolicyJSONRequestBody defines body for PreviewPolicy for application/json ContentType.
type PreviewPolicyJSONRequestBody = PolicyPreviewRequest

// ReplacePricesJSONRequestBody defines body for ReplacePrices for application/json ContentType.
type ReplacePricesJSONRequestBody = ReplacePricesJSONBody

// CompleteProviderLoginJSONRequestBody defines body for CompleteProviderLogin for application/json ContentType.
type CompleteProviderLoginJSONRequestBody = ProviderLoginCompleteRequest

// StartProviderLoginJSONRequestBody defines body for StartProviderLogin for application/json ContentType.
type StartProviderLoginJSONRequestBody = ProviderLoginStartRequest

// UpdateProviderAccountJSONRequestBody defines body for UpdateProviderAccount for application/json ContentType.
type UpdateProviderAccountJSONRequestBody UpdateProviderAccountJSONBody

// UpdateSettingsJSONRequestBody defines body for UpdateSettings for application/json ContentType.
type UpdateSettingsJSONRequestBody = SettingsUpdateRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest

// IssueUserTokenJSONRequestBody defines body for IssueUserToken for application/json ContentType.
type IssueUserTokenJSONRequestBody = IssueTokenRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = PasswordChangeRequest

// IssueMyTokenJSONRequestBody defines body for IssueMyToken for application/json ContentType.
type IssueMyTokenJSONRequestBody = IssueTokenRequest
