// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewAccountMetrics creates a new instance of AccountMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountMetrics {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &AccountMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// AccountMetrics is an autogenerated mock type for the AccountMetrics type
type AccountMetrics struct {
	mock.Mock
}

type AccountMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountMetrics) EXPECT() *AccountMetrics_Expecter {
	return &AccountMetrics_Expecter{mock: &_m.Mock}
}

// ForgetAccount provides a mock function for the type AccountMetrics
func (_mock *AccountMetrics) ForgetAccount(account string, provider string) {
	_mock.Called(account, provider)
	return
}

// AccountMetrics_ForgetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForgetAccount'
type AccountMetrics_ForgetAccount_Call struct {
	*mock.Call
}

// ForgetAccount is a helper method to define mock.On call
//   - account string
//   - provider string
func (_e *AccountMetrics_Expecter) ForgetAccount(account any, provider any) *AccountMetrics_ForgetAccount_Call {
	return &AccountMetrics_ForgetAccount_Call{Call: _e.mock.On("ForgetAccount", account, provider)}
}

func (_c *AccountMetrics_ForgetAccount_Call) Run(run func(account string, provider string)) *AccountMetrics_ForgetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AccountMetrics_ForgetAccount_Call) Return() *AccountMetrics_ForgetAccount_Call {
	_c.Call.Return()
	return _c
}

func (_c *AccountMetrics_ForgetAccount_Call) RunAndReturn(run func(account string, provider string)) *AccountMetrics_ForgetAccount_Call {
	_c.Run(run)
	return _c
}

// SetAccountDisabled provides a mock function for the type AccountMetrics
func (_mock *AccountMetrics) SetAccountDisabled(account string, provider string, disabled bool) {
	_mock.Called(account, provider, disabled)
	return
}

// AccountMetrics_SetAccountDisabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAccountDisabled'
type AccountMetrics_SetAccountDisabled_Call struct {
	*mock.Call
}

// SetAccountDisabled is a helper method to define mock.On call
//   - account string
//   - provider string
//   - disabled bool
func (_e *AccountMetrics_Expecter) SetAccountDisabled(account any, provider any, disabled any) *AccountMetrics_SetAccountDisabled_Call {
	return &AccountMetrics_SetAccountDisabled_Call{Call: _e.mock.On("SetAccountDisabled", account, provider, disabled)}
}

func (_c *AccountMetrics_SetAccountDisabled_Call) Run(run func(account string, provider string, disabled bool)) *AccountMetrics_SetAccountDisabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AccountMetrics_SetAccountDisabled_Call) Return() *AccountMetrics_SetAccountDisabled_Call {
	_c.Call.Return()
	return _c
}

func (_c *AccountMetrics_SetAccountDisabled_Call) RunAndReturn(run func(account string, provider string, disabled bool)) *AccountMetrics_SetAccountDisabled_Call {
	_c.Run(run)
	return _c
}
