// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/elleqt/llm-proxy-backend/internal/app"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewActivityRepo creates a new instance of ActivityRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &ActivityRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// ActivityRepo is an autogenerated mock type for the ActivityRepo type
type ActivityRepo struct {
	mock.Mock
}

type ActivityRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ActivityRepo) EXPECT() *ActivityRepo_Expecter {
	return &ActivityRepo_Expecter{mock: &_m.Mock}
}

// RecentAudit provides a mock function for the type ActivityRepo
func (_mock *ActivityRepo) RecentAudit(ctx context.Context, userID uuid.UUID, limit int) ([]app.AuditEvent, error) {
	ret := _mock.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for RecentAudit")
	}

	var r0 []app.AuditEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]app.AuditEvent, error)); ok {
		return returnFunc(ctx, userID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []app.AuditEvent); ok {
		r0 = returnFunc(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]app.AuditEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = returnFunc(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ActivityRepo_RecentAudit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecentAudit'
type ActivityRepo_RecentAudit_Call struct {
	*mock.Call
}

// RecentAudit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
func (_e *ActivityRepo_Expecter) RecentAudit(ctx any, userID any, limit any) *ActivityRepo_RecentAudit_Call {
	return &ActivityRepo_RecentAudit_Call{Call: _e.mock.On("RecentAudit", ctx, userID, limit)}
}

func (_c *ActivityRepo_RecentAudit_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int)) *ActivityRepo_RecentAudit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ActivityRepo_RecentAudit_Call) Return(auditEvents []app.AuditEvent, err error) *ActivityRepo_RecentAudit_Call {
	_c.Call.Return(auditEvents, err)
	return _c
}

func (_c *ActivityRepo_RecentAudit_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, limit int) ([]app.AuditEvent, error)) *ActivityRepo_RecentAudit_Call {
	_c.Call.Return(run)
	return _c
}

// RecentUsage provides a mock function for the type ActivityRepo
func (_mock *ActivityRepo) RecentUsage(ctx context.Context, userID uuid.UUID, limit int) ([]app.UsageEvent, error) {
	ret := _mock.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for RecentUsage")
	}

	var r0 []app.UsageEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]app.UsageEvent, error)); ok {
		return returnFunc(ctx, userID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []app.UsageEvent); ok {
		r0 = returnFunc(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]app.UsageEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = returnFunc(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ActivityRepo_RecentUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecentUsage'
type ActivityRepo_RecentUsage_Call struct {
	*mock.Call
}

// RecentUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
func (_e *ActivityRepo_Expecter) RecentUsage(ctx any, userID any, limit any) *ActivityRepo_RecentUsage_Call {
	return &ActivityRepo_RecentUsage_Call{Call: _e.mock.On("RecentUsage", ctx, userID, limit)}
}

func (_c *ActivityRepo_RecentUsage_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int)) *ActivityRepo_RecentUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ActivityRepo_RecentUsage_Call) Return(usageEvents []app.UsageEvent, err error) *ActivityRepo_RecentUsage_Call {
	_c.Call.Return(usageEvents, err)
	return _c
}

func (_c *ActivityRepo_RecentUsage_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, limit int) ([]app.UsageEvent, error)) *ActivityRepo_RecentUsage_Call {
	_c.Call.Return(run)
	return _c
}
