// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/elleqt/llm-proxy-backend/internal/app"
	mock "github.com/stretchr/testify/mock"
)

// NewAuditSink creates a new instance of AuditSink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditSink(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditSink {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &AuditSink{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// AuditSink is an autogenerated mock type for the AuditSink type
type AuditSink struct {
	mock.Mock
}

type AuditSink_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditSink) EXPECT() *AuditSink_Expecter {
	return &AuditSink_Expecter{mock: &_m.Mock}
}

// Record provides a mock function for the type AuditSink
func (_mock *AuditSink) Record(ctx context.Context, e app.AuditEvent) error {
	ret := _mock.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.AuditEvent) error); ok {
		r0 = returnFunc(ctx, e)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuditSink_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type AuditSink_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - e app.AuditEvent
func (_e *AuditSink_Expecter) Record(ctx any, e any) *AuditSink_Record_Call {
	return &AuditSink_Record_Call{Call: _e.mock.On("Record", ctx, e)}
}

func (_c *AuditSink_Record_Call) Run(run func(ctx context.Context, e app.AuditEvent)) *AuditSink_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.AuditEvent
		if args[1] != nil {
			arg1 = args[1].(app.AuditEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuditSink_Record_Call) Return(err error) *AuditSink_Record_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuditSink_Record_Call) RunAndReturn(run func(ctx context.Context, e app.AuditEvent) error) *AuditSink_Record_Call {
	_c.Call.Return(run)
	return _c
}
