// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/router-for-me/CLIProxyAPI/v7/sdk/config"
	mock "github.com/stretchr/testify/mock"
)

// NewConfigPusher creates a new instance of ConfigPusher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigPusher(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigPusher {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &ConfigPusher{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// ConfigPusher is an autogenerated mock type for the ConfigPusher type
type ConfigPusher struct {
	mock.Mock
}

type ConfigPusher_Expecter struct {
	mock *mock.Mock
}

func (_m *ConfigPusher) EXPECT() *ConfigPusher_Expecter {
	return &ConfigPusher_Expecter{mock: &_m.Mock}
}

// CurrentConfig provides a mock function for the type ConfigPusher
func (_mock *ConfigPusher) CurrentConfig() *config.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CurrentConfig")
	}

	var r0 *config.Config
	if returnFunc, ok := ret.Get(0).(func() *config.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Config)
		}
	}
	return r0
}

// ConfigPusher_CurrentConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentConfig'
type ConfigPusher_CurrentConfig_Call struct {
	*mock.Call
}

// CurrentConfig is a helper method to define mock.On call
func (_e *ConfigPusher_Expecter) CurrentConfig() *ConfigPusher_CurrentConfig_Call {
	return &ConfigPusher_CurrentConfig_Call{Call: _e.mock.On("CurrentConfig")}
}

func (_c *ConfigPusher_CurrentConfig_Call) Run(run func()) *ConfigPusher_CurrentConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPusher_CurrentConfig_Call) Return(config1 *config.Config) *ConfigPusher_CurrentConfig_Call {
	_c.Call.Return(config1)
	return _c
}

func (_c *ConfigPusher_CurrentConfig_Call) RunAndReturn(run func() *config.Config) *ConfigPusher_CurrentConfig_Call {
	_c.Call.Return(run)
	return _c
}

// PushConfig provides a mock function for the type ConfigPusher
func (_mock *ConfigPusher) PushConfig(cfg *config.Config) error {
	ret := _mock.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for PushConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*config.Config) error); ok {
		r0 = returnFunc(cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ConfigPusher_PushConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushConfig'
type ConfigPusher_PushConfig_Call struct {
	*mock.Call
}

// PushConfig is a helper method to define mock.On call
//   - cfg *config.Config
func (_e *ConfigPusher_Expecter) PushConfig(cfg any) *ConfigPusher_PushConfig_Call {
	return &ConfigPusher_PushConfig_Call{Call: _e.mock.On("PushConfig", cfg)}
}

func (_c *ConfigPusher_PushConfig_Call) Run(run func(cfg *config.Config)) *ConfigPusher_PushConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *config.Config
		if args[0] != nil {
			arg0 = args[0].(*config.Config)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigPusher_PushConfig_Call) Return(err error) *ConfigPusher_PushConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ConfigPusher_PushConfig_Call) RunAndReturn(run func(cfg *config.Config) error) *ConfigPusher_PushConfig_Call {
	_c.Call.Return(run)
	return _c
}
