// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewCostVisibility creates a new instance of CostVisibility. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCostVisibility(t interface {
	mock.TestingT
	Cleanup(func())
}) *CostVisibility {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &CostVisibility{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// CostVisibility is an autogenerated mock type for the CostVisibility type
type CostVisibility struct {
	mock.Mock
}

type CostVisibility_Expecter struct {
	mock *mock.Mock
}

func (_m *CostVisibility) EXPECT() *CostVisibility_Expecter {
	return &CostVisibility_Expecter{mock: &_m.Mock}
}

// CostsVisible provides a mock function for the type CostVisibility
func (_mock *CostVisibility) CostsVisible() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CostsVisible")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// CostVisibility_CostsVisible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CostsVisible'
type CostVisibility_CostsVisible_Call struct {
	*mock.Call
}

// CostsVisible is a helper method to define mock.On call
func (_e *CostVisibility_Expecter) CostsVisible() *CostVisibility_CostsVisible_Call {
	return &CostVisibility_CostsVisible_Call{Call: _e.mock.On("CostsVisible")}
}

func (_c *CostVisibility_CostsVisible_Call) Run(run func()) *CostVisibility_CostsVisible_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CostVisibility_CostsVisible_Call) Return(b bool) *CostVisibility_CostsVisible_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *CostVisibility_CostsVisible_Call) RunAndReturn(run func() bool) *CostVisibility_CostsVisible_Call {
	_c.Call.Return(run)
	return _c
}
