// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/elleqt/llm-proxy-backend/internal/app"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewIdentityRepo creates a new instance of IdentityRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentityRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentityRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &IdentityRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// IdentityRepo is an autogenerated mock type for the IdentityRepo type
type IdentityRepo struct {
	mock.Mock
}

type IdentityRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *IdentityRepo) EXPECT() *IdentityRepo_Expecter {
	return &IdentityRepo_Expecter{mock: &_m.Mock}
}

// BySubject provides a mock function for the type IdentityRepo
func (_mock *IdentityRepo) BySubject(ctx context.Context, issuer string, subject string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, issuer, subject)

	if len(ret) == 0 {
		panic("no return value specified for BySubject")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, issuer, subject)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, issuer, subject)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, issuer, subject)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IdentityRepo_BySubject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BySubject'
type IdentityRepo_BySubject_Call struct {
	*mock.Call
}

// BySubject is a helper method to define mock.On call
//   - ctx context.Context
//   - issuer string
//   - subject string
func (_e *IdentityRepo_Expecter) BySubject(ctx any, issuer any, subject any) *IdentityRepo_BySubject_Call {
	return &IdentityRepo_BySubject_Call{Call: _e.mock.On("BySubject", ctx, issuer, subject)}
}

func (_c *IdentityRepo_BySubject_Call) Run(run func(ctx context.Context, issuer string, subject string)) *IdentityRepo_BySubject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IdentityRepo_BySubject_Call) Return(uUID uuid.UUID, err error) *IdentityRepo_BySubject_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *IdentityRepo_BySubject_Call) RunAndReturn(run func(ctx context.Context, issuer string, subject string) (uuid.UUID, error)) *IdentityRepo_BySubject_Call {
	_c.Call.Return(run)
	return _c
}

// ConsumePending provides a mock function for the type IdentityRepo
func (_mock *IdentityRepo) ConsumePending(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ConsumePending")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IdentityRepo_ConsumePending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumePending'
type IdentityRepo_ConsumePending_Call struct {
	*mock.Call
}

// ConsumePending is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *IdentityRepo_Expecter) ConsumePending(ctx any, userID any) *IdentityRepo_ConsumePending_Call {
	return &IdentityRepo_ConsumePending_Call{Call: _e.mock.On("ConsumePending", ctx, userID)}
}

func (_c *IdentityRepo_ConsumePending_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *IdentityRepo_ConsumePending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IdentityRepo_ConsumePending_Call) Return(err error) *IdentityRepo_ConsumePending_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IdentityRepo_ConsumePending_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *IdentityRepo_ConsumePending_Call {
	_c.Call.Return(run)
	return _c
}

// Invite provides a mock function for the type IdentityRepo
func (_mock *IdentityRepo) Invite(ctx context.Context, userID uuid.UUID, inv app.Invitation) error {
	ret := _mock.Called(ctx, userID, inv)

	if len(ret) == 0 {
		panic("no return value specified for Invite")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, app.Invitation) error); ok {
		r0 = returnFunc(ctx, userID, inv)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IdentityRepo_Invite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invite'
type IdentityRepo_Invite_Call struct {
	*mock.Call
}

// Invite is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - inv app.Invitation
func (_e *IdentityRepo_Expecter) Invite(ctx any, userID any, inv any) *IdentityRepo_Invite_Call {
	return &IdentityRepo_Invite_Call{Call: _e.mock.On("Invite", ctx, userID, inv)}
}

func (_c *IdentityRepo_Invite_Call) Run(run func(ctx context.Context, userID uuid.UUID, inv app.Invitation)) *IdentityRepo_Invite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 app.Invitation
		if args[2] != nil {
			arg2 = args[2].(app.Invitation)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IdentityRepo_Invite_Call) Return(err error) *IdentityRepo_Invite_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IdentityRepo_Invite_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, inv app.Invitation) error) *IdentityRepo_Invite_Call {
	_c.Call.Return(run)
	return _c
}

// Link provides a mock function for the type IdentityRepo
func (_mock *IdentityRepo) Link(ctx context.Context, userID uuid.UUID, issuer string, subject string) error {
	ret := _mock.Called(ctx, userID, issuer, subject)

	if len(ret) == 0 {
		panic("no return value specified for Link")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = returnFunc(ctx, userID, issuer, subject)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IdentityRepo_Link_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Link'
type IdentityRepo_Link_Call struct {
	*mock.Call
}

// Link is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - issuer string
//   - subject string
func (_e *IdentityRepo_Expecter) Link(ctx any, userID any, issuer any, subject any) *IdentityRepo_Link_Call {
	return &IdentityRepo_Link_Call{Call: _e.mock.On("Link", ctx, userID, issuer, subject)}
}

func (_c *IdentityRepo_Link_Call) Run(run func(ctx context.Context, userID uuid.UUID, issuer string, subject string)) *IdentityRepo_Link_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *IdentityRepo_Link_Call) Return(err error) *IdentityRepo_Link_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IdentityRepo_Link_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, issuer string, subject string) error) *IdentityRepo_Link_Call {
	_c.Call.Return(run)
	return _c
}

// PendingByEmail provides a mock function for the type IdentityRepo
func (_mock *IdentityRepo) PendingByEmail(ctx context.Context, issuer string, email string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, issuer, email)

	if len(ret) == 0 {
		panic("no return value specified for PendingByEmail")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, issuer, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, issuer, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, issuer, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IdentityRepo_PendingByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PendingByEmail'
type IdentityRepo_PendingByEmail_Call struct {
	*mock.Call
}

// PendingByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - issuer string
//   - email string
func (_e *IdentityRepo_Expecter) PendingByEmail(ctx any, issuer any, email any) *IdentityRepo_PendingByEmail_Call {
	return &IdentityRepo_PendingByEmail_Call{Call: _e.mock.On("PendingByEmail", ctx, issuer, email)}
}

func (_c *IdentityRepo_PendingByEmail_Call) Run(run func(ctx context.Context, issuer string, email string)) *IdentityRepo_PendingByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IdentityRepo_PendingByEmail_Call) Return(uUID uuid.UUID, err error) *IdentityRepo_PendingByEmail_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *IdentityRepo_PendingByEmail_Call) RunAndReturn(run func(ctx context.Context, issuer string, email string) (uuid.UUID, error)) *IdentityRepo_PendingByEmail_Call {
	_c.Call.Return(run)
	return _c
}
