// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/elleqt/llm-proxy-backend/internal/app"
	mock "github.com/stretchr/testify/mock"
)

// NewIdentityProvider creates a new instance of IdentityProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentityProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentityProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &IdentityProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// IdentityProvider is an autogenerated mock type for the IdentityProvider type
type IdentityProvider struct {
	mock.Mock
}

type IdentityProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *IdentityProvider) EXPECT() *IdentityProvider_Expecter {
	return &IdentityProvider_Expecter{mock: &_m.Mock}
}

// AuthURL provides a mock function for the type IdentityProvider
func (_mock *IdentityProvider) AuthURL(ch app.Challenge) string {
	ret := _mock.Called(ch)

	if len(ret) == 0 {
		panic("no return value specified for AuthURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(app.Challenge) string); ok {
		r0 = returnFunc(ch)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// IdentityProvider_AuthURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthURL'
type IdentityProvider_AuthURL_Call struct {
	*mock.Call
}

// AuthURL is a helper method to define mock.On call
//   - ch app.Challenge
func (_e *IdentityProvider_Expecter) AuthURL(ch any) *IdentityProvider_AuthURL_Call {
	return &IdentityProvider_AuthURL_Call{Call: _e.mock.On("AuthURL", ch)}
}

func (_c *IdentityProvider_AuthURL_Call) Run(run func(ch app.Challenge)) *IdentityProvider_AuthURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 app.Challenge
		if args[0] != nil {
			arg0 = args[0].(app.Challenge)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IdentityProvider_AuthURL_Call) Return(s string) *IdentityProvider_AuthURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *IdentityProvider_AuthURL_Call) RunAndReturn(run func(ch app.Challenge) string) *IdentityProvider_AuthURL_Call {
	_c.Call.Return(run)
	return _c
}

// Exchange provides a mock function for the type IdentityProvider
func (_mock *IdentityProvider) Exchange(ctx context.Context, code string, ch app.Challenge) (app.Claims, error) {
	ret := _mock.Called(ctx, code, ch)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 app.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, app.Challenge) (app.Claims, error)); ok {
		return returnFunc(ctx, code, ch)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, app.Challenge) app.Claims); ok {
		r0 = returnFunc(ctx, code, ch)
	} else {
		r0 = ret.Get(0).(app.Claims)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, app.Challenge) error); ok {
		r1 = returnFunc(ctx, code, ch)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IdentityProvider_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type IdentityProvider_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - ch app.Challenge
func (_e *IdentityProvider_Expecter) Exchange(ctx any, code any, ch any) *IdentityProvider_Exchange_Call {
	return &IdentityProvider_Exchange_Call{Call: _e.mock.On("Exchange", ctx, code, ch)}
}

func (_c *IdentityProvider_Exchange_Call) Run(run func(ctx context.Context, code string, ch app.Challenge)) *IdentityProvider_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 app.Challenge
		if args[2] != nil {
			arg2 = args[2].(app.Challenge)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IdentityProvider_Exchange_Call) Return(claims app.Claims, err error) *IdentityProvider_Exchange_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *IdentityProvider_Exchange_Call) RunAndReturn(run func(ctx context.Context, code string, ch app.Challenge) (app.Claims, error)) *IdentityProvider_Exchange_Call {
	_c.Call.Return(run)
	return _c
}
