// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"log/slog"

	mock "github.com/stretchr/testify/mock"
)

// NewInfoLogger creates a new instance of InfoLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInfoLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *InfoLogger {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &InfoLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// InfoLogger is an autogenerated mock type for the InfoLogger type
type InfoLogger struct {
	mock.Mock
}

type InfoLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *InfoLogger) EXPECT() *InfoLogger_Expecter {
	return &InfoLogger_Expecter{mock: &_m.Mock}
}

// Info provides a mock function for the type InfoLogger
func (_mock *InfoLogger) Info(msg string, attrs ...slog.Attr) {
	if len(attrs) > 0 {
		_mock.Called(msg, attrs)
	} else {
		_mock.Called(msg)
	}

	return
}

// InfoLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type InfoLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - attrs ...slog.Attr
func (_e *InfoLogger_Expecter) Info(msg any, attrs ...any) *InfoLogger_Info_Call {
	return &InfoLogger_Info_Call{Call: _e.mock.On("Info",
		append([]any{msg}, attrs...)...)}
}

func (_c *InfoLogger_Info_Call) Run(run func(msg string, attrs ...slog.Attr)) *InfoLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []slog.Attr
		var variadicArgs []slog.Attr
		if len(args) > 1 {
			variadicArgs = args[1].([]slog.Attr)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *InfoLogger_Info_Call) Return() *InfoLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *InfoLogger_Info_Call) RunAndReturn(run func(msg string, attrs ...slog.Attr)) *InfoLogger_Info_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type InfoLogger
func (_mock *InfoLogger) Warn(msg string, attrs ...slog.Attr) {
	if len(attrs) > 0 {
		_mock.Called(msg, attrs)
	} else {
		_mock.Called(msg)
	}

	return
}

// InfoLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type InfoLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - msg string
//   - attrs ...slog.Attr
func (_e *InfoLogger_Expecter) Warn(msg any, attrs ...any) *InfoLogger_Warn_Call {
	return &InfoLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]any{msg}, attrs...)...)}
}

func (_c *InfoLogger_Warn_Call) Run(run func(msg string, attrs ...slog.Attr)) *InfoLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []slog.Attr
		var variadicArgs []slog.Attr
		if len(args) > 1 {
			variadicArgs = args[1].([]slog.Attr)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *InfoLogger_Warn_Call) Return() *InfoLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *InfoLogger_Warn_Call) RunAndReturn(run func(msg string, attrs ...slog.Attr)) *InfoLogger_Warn_Call {
	_c.Run(run)
	return _c
}
