// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"log/slog"

	mock "github.com/stretchr/testify/mock"
)

// NewLogger creates a new instance of Logger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Logger {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

type Logger_Expecter struct {
	mock *mock.Mock
}

func (_m *Logger) EXPECT() *Logger_Expecter {
	return &Logger_Expecter{mock: &_m.Mock}
}

// Warn provides a mock function for the type Logger
func (_mock *Logger) Warn(msg string, attrs ...slog.Attr) {
	if len(attrs) > 0 {
		_mock.Called(msg, attrs)
	} else {
		_mock.Called(msg)
	}

	return
}

// Logger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type Logger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - msg string
//   - attrs ...slog.Attr
func (_e *Logger_Expecter) Warn(msg any, attrs ...any) *Logger_Warn_Call {
	return &Logger_Warn_Call{Call: _e.mock.On("Warn",
		append([]any{msg}, attrs...)...)}
}

func (_c *Logger_Warn_Call) Run(run func(msg string, attrs ...slog.Attr)) *Logger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []slog.Attr
		var variadicArgs []slog.Attr
		if len(args) > 1 {
			variadicArgs = args[1].([]slog.Attr)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Logger_Warn_Call) Return() *Logger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_Warn_Call) RunAndReturn(run func(msg string, attrs ...slog.Attr)) *Logger_Warn_Call {
	_c.Run(run)
	return _c
}
