// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewLoginAttemptRepo creates a new instance of LoginAttemptRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoginAttemptRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoginAttemptRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &LoginAttemptRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// LoginAttemptRepo is an autogenerated mock type for the LoginAttemptRepo type
type LoginAttemptRepo struct {
	mock.Mock
}

type LoginAttemptRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *LoginAttemptRepo) EXPECT() *LoginAttemptRepo_Expecter {
	return &LoginAttemptRepo_Expecter{mock: &_m.Mock}
}

// Charge provides a mock function for the type LoginAttemptRepo
func (_mock *LoginAttemptRepo) Charge(ctx context.Context, email string, maxFailures int, now time.Time, lockUntil time.Time) (int, *time.Time, error) {
	ret := _mock.Called(ctx, email, maxFailures, now, lockUntil)

	if len(ret) == 0 {
		panic("no return value specified for Charge")
	}

	var r0 int
	var r1 *time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, time.Time, time.Time) (int, *time.Time, error)); ok {
		return returnFunc(ctx, email, maxFailures, now, lockUntil)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, time.Time, time.Time) int); ok {
		r0 = returnFunc(ctx, email, maxFailures, now, lockUntil)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, time.Time, time.Time) *time.Time); ok {
		r1 = returnFunc(ctx, email, maxFailures, now, lockUntil)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*time.Time)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int, time.Time, time.Time) error); ok {
		r2 = returnFunc(ctx, email, maxFailures, now, lockUntil)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// LoginAttemptRepo_Charge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Charge'
type LoginAttemptRepo_Charge_Call struct {
	*mock.Call
}

// Charge is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - maxFailures int
//   - now time.Time
//   - lockUntil time.Time
func (_e *LoginAttemptRepo_Expecter) Charge(ctx any, email any, maxFailures any, now any, lockUntil any) *LoginAttemptRepo_Charge_Call {
	return &LoginAttemptRepo_Charge_Call{Call: _e.mock.On("Charge", ctx, email, maxFailures, now, lockUntil)}
}

func (_c *LoginAttemptRepo_Charge_Call) Run(run func(ctx context.Context, email string, maxFailures int, now time.Time, lockUntil time.Time)) *LoginAttemptRepo_Charge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *LoginAttemptRepo_Charge_Call) Return(count int, lockedUntil *time.Time, err error) *LoginAttemptRepo_Charge_Call {
	_c.Call.Return(count, lockedUntil, err)
	return _c
}

func (_c *LoginAttemptRepo_Charge_Call) RunAndReturn(run func(ctx context.Context, email string, maxFailures int, now time.Time, lockUntil time.Time) (int, *time.Time, error)) *LoginAttemptRepo_Charge_Call {
	_c.Call.Return(run)
	return _c
}

// Clear provides a mock function for the type LoginAttemptRepo
func (_mock *LoginAttemptRepo) Clear(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LoginAttemptRepo_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type LoginAttemptRepo_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *LoginAttemptRepo_Expecter) Clear(ctx any, email any) *LoginAttemptRepo_Clear_Call {
	return &LoginAttemptRepo_Clear_Call{Call: _e.mock.On("Clear", ctx, email)}
}

func (_c *LoginAttemptRepo_Clear_Call) Run(run func(ctx context.Context, email string)) *LoginAttemptRepo_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoginAttemptRepo_Clear_Call) Return(err error) *LoginAttemptRepo_Clear_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LoginAttemptRepo_Clear_Call) RunAndReturn(run func(ctx context.Context, email string) error) *LoginAttemptRepo_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// Failures provides a mock function for the type LoginAttemptRepo
func (_mock *LoginAttemptRepo) Failures(ctx context.Context, email string) (int, *time.Time, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for Failures")
	}

	var r0 int
	var r1 *time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, *time.Time, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *time.Time); ok {
		r1 = returnFunc(ctx, email)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*time.Time)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, email)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// LoginAttemptRepo_Failures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Failures'
type LoginAttemptRepo_Failures_Call struct {
	*mock.Call
}

// Failures is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *LoginAttemptRepo_Expecter) Failures(ctx any, email any) *LoginAttemptRepo_Failures_Call {
	return &LoginAttemptRepo_Failures_Call{Call: _e.mock.On("Failures", ctx, email)}
}

func (_c *LoginAttemptRepo_Failures_Call) Run(run func(ctx context.Context, email string)) *LoginAttemptRepo_Failures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LoginAttemptRepo_Failures_Call) Return(count int, lockedUntil *time.Time, err error) *LoginAttemptRepo_Failures_Call {
	_c.Call.Return(count, lockedUntil, err)
	return _c
}

func (_c *LoginAttemptRepo_Failures_Call) RunAndReturn(run func(ctx context.Context, email string) (int, *time.Time, error)) *LoginAttemptRepo_Failures_Call {
	_c.Call.Return(run)
	return _c
}
