// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewModelCatalog creates a new instance of ModelCatalog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelCatalog(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelCatalog {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &ModelCatalog{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// ModelCatalog is an autogenerated mock type for the ModelCatalog type
type ModelCatalog struct {
	mock.Mock
}

type ModelCatalog_Expecter struct {
	mock *mock.Mock
}

func (_m *ModelCatalog) EXPECT() *ModelCatalog_Expecter {
	return &ModelCatalog_Expecter{mock: &_m.Mock}
}

// Models provides a mock function for the type ModelCatalog
func (_mock *ModelCatalog) Models() map[string][]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Models")
	}

	var r0 map[string][]string
	if returnFunc, ok := ret.Get(0).(func() map[string][]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}
	return r0
}

// ModelCatalog_Models_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Models'
type ModelCatalog_Models_Call struct {
	*mock.Call
}

// Models is a helper method to define mock.On call
func (_e *ModelCatalog_Expecter) Models() *ModelCatalog_Models_Call {
	return &ModelCatalog_Models_Call{Call: _e.mock.On("Models")}
}

func (_c *ModelCatalog_Models_Call) Run(run func()) *ModelCatalog_Models_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ModelCatalog_Models_Call) Return(stringToStrings map[string][]string) *ModelCatalog_Models_Call {
	_c.Call.Return(stringToStrings)
	return _c
}

func (_c *ModelCatalog_Models_Call) RunAndReturn(run func() map[string][]string) *ModelCatalog_Models_Call {
	_c.Call.Return(run)
	return _c
}

// ProvidersFor provides a mock function for the type ModelCatalog
func (_mock *ModelCatalog) ProvidersFor(model string) []string {
	ret := _mock.Called(model)

	if len(ret) == 0 {
		panic("no return value specified for ProvidersFor")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// ModelCatalog_ProvidersFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProvidersFor'
type ModelCatalog_ProvidersFor_Call struct {
	*mock.Call
}

// ProvidersFor is a helper method to define mock.On call
//   - model string
func (_e *ModelCatalog_Expecter) ProvidersFor(model any) *ModelCatalog_ProvidersFor_Call {
	return &ModelCatalog_ProvidersFor_Call{Call: _e.mock.On("ProvidersFor", model)}
}

func (_c *ModelCatalog_ProvidersFor_Call) Run(run func(model string)) *ModelCatalog_ProvidersFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ModelCatalog_ProvidersFor_Call) Return(strings []string) *ModelCatalog_ProvidersFor_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *ModelCatalog_ProvidersFor_Call) RunAndReturn(run func(model string) []string) *ModelCatalog_ProvidersFor_Call {
	_c.Call.Return(run)
	return _c
}
