// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewPasswordRepo creates a new instance of PasswordRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &PasswordRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// PasswordRepo is an autogenerated mock type for the PasswordRepo type
type PasswordRepo struct {
	mock.Mock
}

type PasswordRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *PasswordRepo) EXPECT() *PasswordRepo_Expecter {
	return &PasswordRepo_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type PasswordRepo
func (_mock *PasswordRepo) Get(ctx context.Context, userID uuid.UUID) (string, *time.Time, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 *time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, *time.Time, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) *time.Time); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*time.Time)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// PasswordRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PasswordRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *PasswordRepo_Expecter) Get(ctx any, userID any) *PasswordRepo_Get_Call {
	return &PasswordRepo_Get_Call{Call: _e.mock.On("Get", ctx, userID)}
}

func (_c *PasswordRepo_Get_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *PasswordRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasswordRepo_Get_Call) Return(hash string, expiresAt *time.Time, err error) *PasswordRepo_Get_Call {
	_c.Call.Return(hash, expiresAt, err)
	return _c
}

func (_c *PasswordRepo_Get_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (string, *time.Time, error)) *PasswordRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type PasswordRepo
func (_mock *PasswordRepo) Set(ctx context.Context, userID uuid.UUID, hash string, expiresAt *time.Time) error {
	ret := _mock.Called(ctx, userID, hash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, *time.Time) error); ok {
		r0 = returnFunc(ctx, userID, hash, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PasswordRepo_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type PasswordRepo_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - hash string
//   - expiresAt *time.Time
func (_e *PasswordRepo_Expecter) Set(ctx any, userID any, hash any, expiresAt any) *PasswordRepo_Set_Call {
	return &PasswordRepo_Set_Call{Call: _e.mock.On("Set", ctx, userID, hash, expiresAt)}
}

func (_c *PasswordRepo_Set_Call) Run(run func(ctx context.Context, userID uuid.UUID, hash string, expiresAt *time.Time)) *PasswordRepo_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PasswordRepo_Set_Call) Return(err error) *PasswordRepo_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PasswordRepo_Set_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, hash string, expiresAt *time.Time) error) *PasswordRepo_Set_Call {
	_c.Call.Return(run)
	return _c
}
