// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/elleqt/llm-proxy-backend/internal/app"
	mock "github.com/stretchr/testify/mock"
)

// NewPriceRepo creates a new instance of PriceRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &PriceRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// PriceRepo is an autogenerated mock type for the PriceRepo type
type PriceRepo struct {
	mock.Mock
}

type PriceRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *PriceRepo) EXPECT() *PriceRepo_Expecter {
	return &PriceRepo_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type PriceRepo
func (_mock *PriceRepo) List(ctx context.Context) ([]app.ModelPrice, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []app.ModelPrice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]app.ModelPrice, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []app.ModelPrice); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]app.ModelPrice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PriceRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PriceRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PriceRepo_Expecter) List(ctx any) *PriceRepo_List_Call {
	return &PriceRepo_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *PriceRepo_List_Call) Run(run func(ctx context.Context)) *PriceRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PriceRepo_List_Call) Return(modelPrices []app.ModelPrice, err error) *PriceRepo_List_Call {
	_c.Call.Return(modelPrices, err)
	return _c
}

func (_c *PriceRepo_List_Call) RunAndReturn(run func(ctx context.Context) ([]app.ModelPrice, error)) *PriceRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// Replace provides a mock function for the type PriceRepo
func (_mock *PriceRepo) Replace(ctx context.Context, prices []app.ModelPrice, at time.Time) error {
	ret := _mock.Called(ctx, prices, at)

	if len(ret) == 0 {
		panic("no return value specified for Replace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []app.ModelPrice, time.Time) error); ok {
		r0 = returnFunc(ctx, prices, at)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PriceRepo_Replace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Replace'
type PriceRepo_Replace_Call struct {
	*mock.Call
}

// Replace is a helper method to define mock.On call
//   - ctx context.Context
//   - prices []app.ModelPrice
//   - at time.Time
func (_e *PriceRepo_Expecter) Replace(ctx any, prices any, at any) *PriceRepo_Replace_Call {
	return &PriceRepo_Replace_Call{Call: _e.mock.On("Replace", ctx, prices, at)}
}

func (_c *PriceRepo_Replace_Call) Run(run func(ctx context.Context, prices []app.ModelPrice, at time.Time)) *PriceRepo_Replace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []app.ModelPrice
		if args[1] != nil {
			arg1 = args[1].([]app.ModelPrice)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PriceRepo_Replace_Call) Return(err error) *PriceRepo_Replace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PriceRepo_Replace_Call) RunAndReturn(run func(ctx context.Context, prices []app.ModelPrice, at time.Time) error) *PriceRepo_Replace_Call {
	_c.Call.Return(run)
	return _c
}
