// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/elleqt/llm-proxy-backend/internal/app"
	mock "github.com/stretchr/testify/mock"
)

// NewPriceCatalogSource creates a new instance of PriceCatalogSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceCatalogSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceCatalogSource {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &PriceCatalogSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// PriceCatalogSource is an autogenerated mock type for the PriceCatalogSource type
type PriceCatalogSource struct {
	mock.Mock
}

type PriceCatalogSource_Expecter struct {
	mock *mock.Mock
}

func (_m *PriceCatalogSource) EXPECT() *PriceCatalogSource_Expecter {
	return &PriceCatalogSource_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type PriceCatalogSource
func (_mock *PriceCatalogSource) Fetch(ctx context.Context, since app.CatalogValidators) (app.CatalogFetch, error) {
	ret := _mock.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 app.CatalogFetch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.CatalogValidators) (app.CatalogFetch, error)); ok {
		return returnFunc(ctx, since)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.CatalogValidators) app.CatalogFetch); ok {
		r0 = returnFunc(ctx, since)
	} else {
		r0 = ret.Get(0).(app.CatalogFetch)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.CatalogValidators) error); ok {
		r1 = returnFunc(ctx, since)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PriceCatalogSource_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type PriceCatalogSource_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - since app.CatalogValidators
func (_e *PriceCatalogSource_Expecter) Fetch(ctx any, since any) *PriceCatalogSource_Fetch_Call {
	return &PriceCatalogSource_Fetch_Call{Call: _e.mock.On("Fetch", ctx, since)}
}

func (_c *PriceCatalogSource_Fetch_Call) Run(run func(ctx context.Context, since app.CatalogValidators)) *PriceCatalogSource_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.CatalogValidators
		if args[1] != nil {
			arg1 = args[1].(app.CatalogValidators)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PriceCatalogSource_Fetch_Call) Return(catalogFetch app.CatalogFetch, err error) *PriceCatalogSource_Fetch_Call {
	_c.Call.Return(catalogFetch, err)
	return _c
}

func (_c *PriceCatalogSource_Fetch_Call) RunAndReturn(run func(ctx context.Context, since app.CatalogValidators) (app.CatalogFetch, error)) *PriceCatalogSource_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// Fingerprint provides a mock function for the type PriceCatalogSource
func (_mock *PriceCatalogSource) Fingerprint() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Fingerprint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// PriceCatalogSource_Fingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fingerprint'
type PriceCatalogSource_Fingerprint_Call struct {
	*mock.Call
}

// Fingerprint is a helper method to define mock.On call
func (_e *PriceCatalogSource_Expecter) Fingerprint() *PriceCatalogSource_Fingerprint_Call {
	return &PriceCatalogSource_Fingerprint_Call{Call: _e.mock.On("Fingerprint")}
}

func (_c *PriceCatalogSource_Fingerprint_Call) Run(run func()) *PriceCatalogSource_Fingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PriceCatalogSource_Fingerprint_Call) Return(s string) *PriceCatalogSource_Fingerprint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *PriceCatalogSource_Fingerprint_Call) RunAndReturn(run func() string) *PriceCatalogSource_Fingerprint_Call {
	_c.Call.Return(run)
	return _c
}
