// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewPriceCatalogMetrics creates a new instance of PriceCatalogMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceCatalogMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceCatalogMetrics {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &PriceCatalogMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// PriceCatalogMetrics is an autogenerated mock type for the PriceCatalogMetrics type
type PriceCatalogMetrics struct {
	mock.Mock
}

type PriceCatalogMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *PriceCatalogMetrics) EXPECT() *PriceCatalogMetrics_Expecter {
	return &PriceCatalogMetrics_Expecter{mock: &_m.Mock}
}

// ObservePriceCatalogFailure provides a mock function for the type PriceCatalogMetrics
func (_mock *PriceCatalogMetrics) ObservePriceCatalogFailure() {
	_mock.Called()
	return
}

// PriceCatalogMetrics_ObservePriceCatalogFailure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObservePriceCatalogFailure'
type PriceCatalogMetrics_ObservePriceCatalogFailure_Call struct {
	*mock.Call
}

// ObservePriceCatalogFailure is a helper method to define mock.On call
func (_e *PriceCatalogMetrics_Expecter) ObservePriceCatalogFailure() *PriceCatalogMetrics_ObservePriceCatalogFailure_Call {
	return &PriceCatalogMetrics_ObservePriceCatalogFailure_Call{Call: _e.mock.On("ObservePriceCatalogFailure")}
}

func (_c *PriceCatalogMetrics_ObservePriceCatalogFailure_Call) Run(run func()) *PriceCatalogMetrics_ObservePriceCatalogFailure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PriceCatalogMetrics_ObservePriceCatalogFailure_Call) Return() *PriceCatalogMetrics_ObservePriceCatalogFailure_Call {
	_c.Call.Return()
	return _c
}

func (_c *PriceCatalogMetrics_ObservePriceCatalogFailure_Call) RunAndReturn(run func()) *PriceCatalogMetrics_ObservePriceCatalogFailure_Call {
	_c.Run(run)
	return _c
}

// SetPriceCatalog provides a mock function for the type PriceCatalogMetrics
func (_mock *PriceCatalogMetrics) SetPriceCatalog(models int, checkedAt time.Time) {
	_mock.Called(models, checkedAt)
	return
}

// PriceCatalogMetrics_SetPriceCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPriceCatalog'
type PriceCatalogMetrics_SetPriceCatalog_Call struct {
	*mock.Call
}

// SetPriceCatalog is a helper method to define mock.On call
//   - models int
//   - checkedAt time.Time
func (_e *PriceCatalogMetrics_Expecter) SetPriceCatalog(models any, checkedAt any) *PriceCatalogMetrics_SetPriceCatalog_Call {
	return &PriceCatalogMetrics_SetPriceCatalog_Call{Call: _e.mock.On("SetPriceCatalog", models, checkedAt)}
}

func (_c *PriceCatalogMetrics_SetPriceCatalog_Call) Run(run func(models int, checkedAt time.Time)) *PriceCatalogMetrics_SetPriceCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PriceCatalogMetrics_SetPriceCatalog_Call) Return() *PriceCatalogMetrics_SetPriceCatalog_Call {
	_c.Call.Return()
	return _c
}

func (_c *PriceCatalogMetrics_SetPriceCatalog_Call) RunAndReturn(run func(models int, checkedAt time.Time)) *PriceCatalogMetrics_SetPriceCatalog_Call {
	_c.Run(run)
	return _c
}
