// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/elleqt/llm-proxy-backend/internal/app"
	mock "github.com/stretchr/testify/mock"
)

// NewPriceSink creates a new instance of PriceSink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceSink(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceSink {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &PriceSink{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// PriceSink is an autogenerated mock type for the PriceSink type
type PriceSink struct {
	mock.Mock
}

type PriceSink_Expecter struct {
	mock *mock.Mock
}

func (_m *PriceSink) EXPECT() *PriceSink_Expecter {
	return &PriceSink_Expecter{mock: &_m.Mock}
}

// SetPrices provides a mock function for the type PriceSink
func (_mock *PriceSink) SetPrices(prices []app.ModelPrice) {
	_mock.Called(prices)
	return
}

// PriceSink_SetPrices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPrices'
type PriceSink_SetPrices_Call struct {
	*mock.Call
}

// SetPrices is a helper method to define mock.On call
//   - prices []app.ModelPrice
func (_e *PriceSink_Expecter) SetPrices(prices any) *PriceSink_SetPrices_Call {
	return &PriceSink_SetPrices_Call{Call: _e.mock.On("SetPrices", prices)}
}

func (_c *PriceSink_SetPrices_Call) Run(run func(prices []app.ModelPrice)) *PriceSink_SetPrices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []app.ModelPrice
		if args[0] != nil {
			arg0 = args[0].([]app.ModelPrice)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PriceSink_SetPrices_Call) Return() *PriceSink_SetPrices_Call {
	_c.Call.Return()
	return _c
}

func (_c *PriceSink_SetPrices_Call) RunAndReturn(run func(prices []app.ModelPrice)) *PriceSink_SetPrices_Call {
	_c.Run(run)
	return _c
}
