// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/elleqt/llm-proxy-backend/internal/app"
	mock "github.com/stretchr/testify/mock"
)

// NewPriceCatalogRepo creates a new instance of PriceCatalogRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceCatalogRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceCatalogRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &PriceCatalogRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// PriceCatalogRepo is an autogenerated mock type for the PriceCatalogRepo type
type PriceCatalogRepo struct {
	mock.Mock
}

type PriceCatalogRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *PriceCatalogRepo) EXPECT() *PriceCatalogRepo_Expecter {
	return &PriceCatalogRepo_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type PriceCatalogRepo
func (_mock *PriceCatalogRepo) List(ctx context.Context) ([]app.ModelPrice, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []app.ModelPrice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]app.ModelPrice, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []app.ModelPrice); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]app.ModelPrice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PriceCatalogRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PriceCatalogRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PriceCatalogRepo_Expecter) List(ctx any) *PriceCatalogRepo_List_Call {
	return &PriceCatalogRepo_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *PriceCatalogRepo_List_Call) Run(run func(ctx context.Context)) *PriceCatalogRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PriceCatalogRepo_List_Call) Return(modelPrices []app.ModelPrice, err error) *PriceCatalogRepo_List_Call {
	_c.Call.Return(modelPrices, err)
	return _c
}

func (_c *PriceCatalogRepo_List_Call) RunAndReturn(run func(ctx context.Context) ([]app.ModelPrice, error)) *PriceCatalogRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// Replace provides a mock function for the type PriceCatalogRepo
func (_mock *PriceCatalogRepo) Replace(ctx context.Context, prices []app.ModelPrice, state app.CatalogState, at time.Time) error {
	ret := _mock.Called(ctx, prices, state, at)

	if len(ret) == 0 {
		panic("no return value specified for Replace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []app.ModelPrice, app.CatalogState, time.Time) error); ok {
		r0 = returnFunc(ctx, prices, state, at)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PriceCatalogRepo_Replace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Replace'
type PriceCatalogRepo_Replace_Call struct {
	*mock.Call
}

// Replace is a helper method to define mock.On call
//   - ctx context.Context
//   - prices []app.ModelPrice
//   - state app.CatalogState
//   - at time.Time
func (_e *PriceCatalogRepo_Expecter) Replace(ctx any, prices any, state any, at any) *PriceCatalogRepo_Replace_Call {
	return &PriceCatalogRepo_Replace_Call{Call: _e.mock.On("Replace", ctx, prices, state, at)}
}

func (_c *PriceCatalogRepo_Replace_Call) Run(run func(ctx context.Context, prices []app.ModelPrice, state app.CatalogState, at time.Time)) *PriceCatalogRepo_Replace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []app.ModelPrice
		if args[1] != nil {
			arg1 = args[1].([]app.ModelPrice)
		}
		var arg2 app.CatalogState
		if args[2] != nil {
			arg2 = args[2].(app.CatalogState)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PriceCatalogRepo_Replace_Call) Return(err error) *PriceCatalogRepo_Replace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PriceCatalogRepo_Replace_Call) RunAndReturn(run func(ctx context.Context, prices []app.ModelPrice, state app.CatalogState, at time.Time) error) *PriceCatalogRepo_Replace_Call {
	_c.Call.Return(run)
	return _c
}

// SetState provides a mock function for the type PriceCatalogRepo
func (_mock *PriceCatalogRepo) SetState(ctx context.Context, state app.CatalogState) error {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for SetState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.CatalogState) error); ok {
		r0 = returnFunc(ctx, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PriceCatalogRepo_SetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetState'
type PriceCatalogRepo_SetState_Call struct {
	*mock.Call
}

// SetState is a helper method to define mock.On call
//   - ctx context.Context
//   - state app.CatalogState
func (_e *PriceCatalogRepo_Expecter) SetState(ctx any, state any) *PriceCatalogRepo_SetState_Call {
	return &PriceCatalogRepo_SetState_Call{Call: _e.mock.On("SetState", ctx, state)}
}

func (_c *PriceCatalogRepo_SetState_Call) Run(run func(ctx context.Context, state app.CatalogState)) *PriceCatalogRepo_SetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.CatalogState
		if args[1] != nil {
			arg1 = args[1].(app.CatalogState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PriceCatalogRepo_SetState_Call) Return(err error) *PriceCatalogRepo_SetState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PriceCatalogRepo_SetState_Call) RunAndReturn(run func(ctx context.Context, state app.CatalogState) error) *PriceCatalogRepo_SetState_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function for the type PriceCatalogRepo
func (_mock *PriceCatalogRepo) State(ctx context.Context) (app.CatalogState, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 app.CatalogState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (app.CatalogState, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) app.CatalogState); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(app.CatalogState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PriceCatalogRepo_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type PriceCatalogRepo_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PriceCatalogRepo_Expecter) State(ctx any) *PriceCatalogRepo_State_Call {
	return &PriceCatalogRepo_State_Call{Call: _e.mock.On("State", ctx)}
}

func (_c *PriceCatalogRepo_State_Call) Run(run func(ctx context.Context)) *PriceCatalogRepo_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PriceCatalogRepo_State_Call) Return(catalogState app.CatalogState, err error) *PriceCatalogRepo_State_Call {
	_c.Call.Return(catalogState, err)
	return _c
}

func (_c *PriceCatalogRepo_State_Call) RunAndReturn(run func(ctx context.Context) (app.CatalogState, error)) *PriceCatalogRepo_State_Call {
	_c.Call.Return(run)
	return _c
}
