// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/elleqt/llm-proxy-backend/internal/app"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewSessionRepo creates a new instance of SessionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &SessionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// SessionRepo is an autogenerated mock type for the SessionRepo type
type SessionRepo struct {
	mock.Mock
}

type SessionRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepo) EXPECT() *SessionRepo_Expecter {
	return &SessionRepo_Expecter{mock: &_m.Mock}
}

// ByHash provides a mock function for the type SessionRepo
func (_mock *SessionRepo) ByHash(ctx context.Context, idHash string) (app.Session, error) {
	ret := _mock.Called(ctx, idHash)

	if len(ret) == 0 {
		panic("no return value specified for ByHash")
	}

	var r0 app.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (app.Session, error)); ok {
		return returnFunc(ctx, idHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) app.Session); ok {
		r0 = returnFunc(ctx, idHash)
	} else {
		r0 = ret.Get(0).(app.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, idHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepo_ByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByHash'
type SessionRepo_ByHash_Call struct {
	*mock.Call
}

// ByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - idHash string
func (_e *SessionRepo_Expecter) ByHash(ctx any, idHash any) *SessionRepo_ByHash_Call {
	return &SessionRepo_ByHash_Call{Call: _e.mock.On("ByHash", ctx, idHash)}
}

func (_c *SessionRepo_ByHash_Call) Run(run func(ctx context.Context, idHash string)) *SessionRepo_ByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepo_ByHash_Call) Return(session app.Session, err error) *SessionRepo_ByHash_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *SessionRepo_ByHash_Call) RunAndReturn(run func(ctx context.Context, idHash string) (app.Session, error)) *SessionRepo_ByHash_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type SessionRepo
func (_mock *SessionRepo) Create(ctx context.Context, s app.Session) error {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.Session) error); ok {
		r0 = returnFunc(ctx, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SessionRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s app.Session
func (_e *SessionRepo_Expecter) Create(ctx any, s any) *SessionRepo_Create_Call {
	return &SessionRepo_Create_Call{Call: _e.mock.On("Create", ctx, s)}
}

func (_c *SessionRepo_Create_Call) Run(run func(ctx context.Context, s app.Session)) *SessionRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.Session
		if args[1] != nil {
			arg1 = args[1].(app.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepo_Create_Call) Return(err error) *SessionRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepo_Create_Call) RunAndReturn(run func(ctx context.Context, s app.Session) error) *SessionRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type SessionRepo
func (_mock *SessionRepo) Delete(ctx context.Context, idHash string) error {
	ret := _mock.Called(ctx, idHash)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, idHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SessionRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - idHash string
func (_e *SessionRepo_Expecter) Delete(ctx any, idHash any) *SessionRepo_Delete_Call {
	return &SessionRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, idHash)}
}

func (_c *SessionRepo_Delete_Call) Run(run func(ctx context.Context, idHash string)) *SessionRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepo_Delete_Call) Return(err error) *SessionRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, idHash string) error) *SessionRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUser provides a mock function for the type SessionRepo
func (_mock *SessionRepo) DeleteByUser(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepo_DeleteByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUser'
type SessionRepo_DeleteByUser_Call struct {
	*mock.Call
}

// DeleteByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *SessionRepo_Expecter) DeleteByUser(ctx any, userID any) *SessionRepo_DeleteByUser_Call {
	return &SessionRepo_DeleteByUser_Call{Call: _e.mock.On("DeleteByUser", ctx, userID)}
}

func (_c *SessionRepo_DeleteByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *SessionRepo_DeleteByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepo_DeleteByUser_Call) Return(err error) *SessionRepo_DeleteByUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepo_DeleteByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *SessionRepo_DeleteByUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserExcept provides a mock function for the type SessionRepo
func (_mock *SessionRepo) DeleteByUserExcept(ctx context.Context, userID uuid.UUID, keepHash string) error {
	ret := _mock.Called(ctx, userID, keepHash)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserExcept")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, userID, keepHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepo_DeleteByUserExcept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserExcept'
type SessionRepo_DeleteByUserExcept_Call struct {
	*mock.Call
}

// DeleteByUserExcept is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - keepHash string
func (_e *SessionRepo_Expecter) DeleteByUserExcept(ctx any, userID any, keepHash any) *SessionRepo_DeleteByUserExcept_Call {
	return &SessionRepo_DeleteByUserExcept_Call{Call: _e.mock.On("DeleteByUserExcept", ctx, userID, keepHash)}
}

func (_c *SessionRepo_DeleteByUserExcept_Call) Run(run func(ctx context.Context, userID uuid.UUID, keepHash string)) *SessionRepo_DeleteByUserExcept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SessionRepo_DeleteByUserExcept_Call) Return(err error) *SessionRepo_DeleteByUserExcept_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepo_DeleteByUserExcept_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, keepHash string) error) *SessionRepo_DeleteByUserExcept_Call {
	_c.Call.Return(run)
	return _c
}
