// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewSettingsRepo creates a new instance of SettingsRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSettingsRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SettingsRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &SettingsRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// SettingsRepo is an autogenerated mock type for the SettingsRepo type
type SettingsRepo struct {
	mock.Mock
}

type SettingsRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *SettingsRepo) EXPECT() *SettingsRepo_Expecter {
	return &SettingsRepo_Expecter{mock: &_m.Mock}
}

// SetUpstreamDocument provides a mock function for the type SettingsRepo
func (_mock *SettingsRepo) SetUpstreamDocument(ctx context.Context, doc string, by uuid.UUID, at time.Time) error {
	ret := _mock.Called(ctx, doc, by, at)

	if len(ret) == 0 {
		panic("no return value specified for SetUpstreamDocument")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, doc, by, at)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SettingsRepo_SetUpstreamDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUpstreamDocument'
type SettingsRepo_SetUpstreamDocument_Call struct {
	*mock.Call
}

// SetUpstreamDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - doc string
//   - by uuid.UUID
//   - at time.Time
func (_e *SettingsRepo_Expecter) SetUpstreamDocument(ctx any, doc any, by any, at any) *SettingsRepo_SetUpstreamDocument_Call {
	return &SettingsRepo_SetUpstreamDocument_Call{Call: _e.mock.On("SetUpstreamDocument", ctx, doc, by, at)}
}

func (_c *SettingsRepo_SetUpstreamDocument_Call) Run(run func(ctx context.Context, doc string, by uuid.UUID, at time.Time)) *SettingsRepo_SetUpstreamDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SettingsRepo_SetUpstreamDocument_Call) Return(err error) *SettingsRepo_SetUpstreamDocument_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SettingsRepo_SetUpstreamDocument_Call) RunAndReturn(run func(ctx context.Context, doc string, by uuid.UUID, at time.Time) error) *SettingsRepo_SetUpstreamDocument_Call {
	_c.Call.Return(run)
	return _c
}

// UpstreamDocument provides a mock function for the type SettingsRepo
func (_mock *SettingsRepo) UpstreamDocument(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UpstreamDocument")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SettingsRepo_UpstreamDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpstreamDocument'
type SettingsRepo_UpstreamDocument_Call struct {
	*mock.Call
}

// UpstreamDocument is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SettingsRepo_Expecter) UpstreamDocument(ctx any) *SettingsRepo_UpstreamDocument_Call {
	return &SettingsRepo_UpstreamDocument_Call{Call: _e.mock.On("UpstreamDocument", ctx)}
}

func (_c *SettingsRepo_UpstreamDocument_Call) Run(run func(ctx context.Context)) *SettingsRepo_UpstreamDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SettingsRepo_UpstreamDocument_Call) Return(s string, err error) *SettingsRepo_UpstreamDocument_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *SettingsRepo_UpstreamDocument_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *SettingsRepo_UpstreamDocument_Call {
	_c.Call.Return(run)
	return _c
}
