// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/elleqt/llm-proxy-backend/internal/domain/limits"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewSpendWindowRepo creates a new instance of SpendWindowRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpendWindowRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpendWindowRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &SpendWindowRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// SpendWindowRepo is an autogenerated mock type for the SpendWindowRepo type
type SpendWindowRepo struct {
	mock.Mock
}

type SpendWindowRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *SpendWindowRepo) EXPECT() *SpendWindowRepo_Expecter {
	return &SpendWindowRepo_Expecter{mock: &_m.Mock}
}

// Open provides a mock function for the type SpendWindowRepo
func (_mock *SpendWindowRepo) Open(ctx context.Context, userID uuid.UUID, open []time.Duration, drop []time.Duration, at time.Time) error {
	ret := _mock.Called(ctx, userID, open, drop, at)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []time.Duration, []time.Duration, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, open, drop, at)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SpendWindowRepo_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type SpendWindowRepo_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - open []time.Duration
//   - drop []time.Duration
//   - at time.Time
func (_e *SpendWindowRepo_Expecter) Open(ctx any, userID any, open any, drop any, at any) *SpendWindowRepo_Open_Call {
	return &SpendWindowRepo_Open_Call{Call: _e.mock.On("Open", ctx, userID, open, drop, at)}
}

func (_c *SpendWindowRepo_Open_Call) Run(run func(ctx context.Context, userID uuid.UUID, open []time.Duration, drop []time.Duration, at time.Time)) *SpendWindowRepo_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []time.Duration
		if args[2] != nil {
			arg2 = args[2].([]time.Duration)
		}
		var arg3 []time.Duration
		if args[3] != nil {
			arg3 = args[3].([]time.Duration)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *SpendWindowRepo_Open_Call) Return(err error) *SpendWindowRepo_Open_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SpendWindowRepo_Open_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, open []time.Duration, drop []time.Duration, at time.Time) error) *SpendWindowRepo_Open_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function for the type SpendWindowRepo
func (_mock *SpendWindowRepo) Reset(ctx context.Context, userID uuid.UUID, window *time.Duration) error {
	ret := _mock.Called(ctx, userID, window)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *time.Duration) error); ok {
		r0 = returnFunc(ctx, userID, window)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SpendWindowRepo_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type SpendWindowRepo_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - window *time.Duration
func (_e *SpendWindowRepo_Expecter) Reset(ctx any, userID any, window any) *SpendWindowRepo_Reset_Call {
	return &SpendWindowRepo_Reset_Call{Call: _e.mock.On("Reset", ctx, userID, window)}
}

func (_c *SpendWindowRepo_Reset_Call) Run(run func(ctx context.Context, userID uuid.UUID, window *time.Duration)) *SpendWindowRepo_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *time.Duration
		if args[2] != nil {
			arg2 = args[2].(*time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SpendWindowRepo_Reset_Call) Return(err error) *SpendWindowRepo_Reset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SpendWindowRepo_Reset_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, window *time.Duration) error) *SpendWindowRepo_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// Windows provides a mock function for the type SpendWindowRepo
func (_mock *SpendWindowRepo) Windows(ctx context.Context, userID uuid.UUID) ([]limits.Window, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Windows")
	}

	var r0 []limits.Window
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]limits.Window, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []limits.Window); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]limits.Window)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SpendWindowRepo_Windows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Windows'
type SpendWindowRepo_Windows_Call struct {
	*mock.Call
}

// Windows is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *SpendWindowRepo_Expecter) Windows(ctx any, userID any) *SpendWindowRepo_Windows_Call {
	return &SpendWindowRepo_Windows_Call{Call: _e.mock.On("Windows", ctx, userID)}
}

func (_c *SpendWindowRepo_Windows_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *SpendWindowRepo_Windows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SpendWindowRepo_Windows_Call) Return(windows []limits.Window, err error) *SpendWindowRepo_Windows_Call {
	_c.Call.Return(windows, err)
	return _c
}

func (_c *SpendWindowRepo_Windows_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]limits.Window, error)) *SpendWindowRepo_Windows_Call {
	_c.Call.Return(run)
	return _c
}
