// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/elleqt/llm-proxy-backend/internal/domain/limits"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewSpendGate creates a new instance of SpendGate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpendGate(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpendGate {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &SpendGate{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// SpendGate is an autogenerated mock type for the SpendGate type
type SpendGate struct {
	mock.Mock
}

type SpendGate_Expecter struct {
	mock *mock.Mock
}

func (_m *SpendGate) EXPECT() *SpendGate_Expecter {
	return &SpendGate_Expecter{mock: &_m.Mock}
}

// Admit provides a mock function for the type SpendGate
func (_mock *SpendGate) Admit(ctx context.Context, userID uuid.UUID, set limits.Set) (limits.Decision, error) {
	ret := _mock.Called(ctx, userID, set)

	if len(ret) == 0 {
		panic("no return value specified for Admit")
	}

	var r0 limits.Decision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, limits.Set) (limits.Decision, error)); ok {
		return returnFunc(ctx, userID, set)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, limits.Set) limits.Decision); ok {
		r0 = returnFunc(ctx, userID, set)
	} else {
		r0 = ret.Get(0).(limits.Decision)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, limits.Set) error); ok {
		r1 = returnFunc(ctx, userID, set)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SpendGate_Admit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Admit'
type SpendGate_Admit_Call struct {
	*mock.Call
}

// Admit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - set limits.Set
func (_e *SpendGate_Expecter) Admit(ctx any, userID any, set any) *SpendGate_Admit_Call {
	return &SpendGate_Admit_Call{Call: _e.mock.On("Admit", ctx, userID, set)}
}

func (_c *SpendGate_Admit_Call) Run(run func(ctx context.Context, userID uuid.UUID, set limits.Set)) *SpendGate_Admit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 limits.Set
		if args[2] != nil {
			arg2 = args[2].(limits.Set)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SpendGate_Admit_Call) Return(decision limits.Decision, err error) *SpendGate_Admit_Call {
	_c.Call.Return(decision, err)
	return _c
}

func (_c *SpendGate_Admit_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, set limits.Set) (limits.Decision, error)) *SpendGate_Admit_Call {
	_c.Call.Return(run)
	return _c
}

// Effective provides a mock function for the type SpendGate
func (_mock *SpendGate) Effective(custom *limits.Set) limits.Set {
	ret := _mock.Called(custom)

	if len(ret) == 0 {
		panic("no return value specified for Effective")
	}

	var r0 limits.Set
	if returnFunc, ok := ret.Get(0).(func(*limits.Set) limits.Set); ok {
		r0 = returnFunc(custom)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(limits.Set)
		}
	}
	return r0
}

// SpendGate_Effective_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Effective'
type SpendGate_Effective_Call struct {
	*mock.Call
}

// Effective is a helper method to define mock.On call
//   - custom *limits.Set
func (_e *SpendGate_Expecter) Effective(custom any) *SpendGate_Effective_Call {
	return &SpendGate_Effective_Call{Call: _e.mock.On("Effective", custom)}
}

func (_c *SpendGate_Effective_Call) Run(run func(custom *limits.Set)) *SpendGate_Effective_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *limits.Set
		if args[0] != nil {
			arg0 = args[0].(*limits.Set)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SpendGate_Effective_Call) Return(set limits.Set) *SpendGate_Effective_Call {
	_c.Call.Return(set)
	return _c
}

func (_c *SpendGate_Effective_Call) RunAndReturn(run func(custom *limits.Set) limits.Set) *SpendGate_Effective_Call {
	_c.Call.Return(run)
	return _c
}
