// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/elleqt/llm-proxy-backend/internal/domain/credentials"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenRepo creates a new instance of TokenRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &TokenRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// TokenRepo is an autogenerated mock type for the TokenRepo type
type TokenRepo struct {
	mock.Mock
}

type TokenRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenRepo) EXPECT() *TokenRepo_Expecter {
	return &TokenRepo_Expecter{mock: &_m.Mock}
}

// ByHash provides a mock function for the type TokenRepo
func (_mock *TokenRepo) ByHash(ctx context.Context, hash string) (credentials.Token, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for ByHash")
	}

	var r0 credentials.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (credentials.Token, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) credentials.Token); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		r0 = ret.Get(0).(credentials.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenRepo_ByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByHash'
type TokenRepo_ByHash_Call struct {
	*mock.Call
}

// ByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *TokenRepo_Expecter) ByHash(ctx any, hash any) *TokenRepo_ByHash_Call {
	return &TokenRepo_ByHash_Call{Call: _e.mock.On("ByHash", ctx, hash)}
}

func (_c *TokenRepo_ByHash_Call) Run(run func(ctx context.Context, hash string)) *TokenRepo_ByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenRepo_ByHash_Call) Return(token credentials.Token, err error) *TokenRepo_ByHash_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *TokenRepo_ByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (credentials.Token, error)) *TokenRepo_ByHash_Call {
	_c.Call.Return(run)
	return _c
}

// ByID provides a mock function for the type TokenRepo
func (_mock *TokenRepo) ByID(ctx context.Context, id uuid.UUID) (credentials.Token, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 credentials.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (credentials.Token, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) credentials.Token); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(credentials.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenRepo_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type TokenRepo_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *TokenRepo_Expecter) ByID(ctx any, id any) *TokenRepo_ByID_Call {
	return &TokenRepo_ByID_Call{Call: _e.mock.On("ByID", ctx, id)}
}

func (_c *TokenRepo_ByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *TokenRepo_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenRepo_ByID_Call) Return(token credentials.Token, err error) *TokenRepo_ByID_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *TokenRepo_ByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (credentials.Token, error)) *TokenRepo_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type TokenRepo
func (_mock *TokenRepo) Create(ctx context.Context, t credentials.Token) error {
	ret := _mock.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, credentials.Token) error); ok {
		r0 = returnFunc(ctx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TokenRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t credentials.Token
func (_e *TokenRepo_Expecter) Create(ctx any, t any) *TokenRepo_Create_Call {
	return &TokenRepo_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *TokenRepo_Create_Call) Run(run func(ctx context.Context, t credentials.Token)) *TokenRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 credentials.Token
		if args[1] != nil {
			arg1 = args[1].(credentials.Token)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenRepo_Create_Call) Return(err error) *TokenRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenRepo_Create_Call) RunAndReturn(run func(ctx context.Context, t credentials.Token) error) *TokenRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type TokenRepo
func (_mock *TokenRepo) ListByUser(ctx context.Context, userID uuid.UUID) ([]credentials.Token, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []credentials.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]credentials.Token, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []credentials.Token); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]credentials.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenRepo_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type TokenRepo_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *TokenRepo_Expecter) ListByUser(ctx any, userID any) *TokenRepo_ListByUser_Call {
	return &TokenRepo_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *TokenRepo_ListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *TokenRepo_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenRepo_ListByUser_Call) Return(tokens []credentials.Token, err error) *TokenRepo_ListByUser_Call {
	_c.Call.Return(tokens, err)
	return _c
}

func (_c *TokenRepo_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]credentials.Token, error)) *TokenRepo_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type TokenRepo
func (_mock *TokenRepo) Save(ctx context.Context, t credentials.Token) error {
	ret := _mock.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, credentials.Token) error); ok {
		r0 = returnFunc(ctx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type TokenRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - t credentials.Token
func (_e *TokenRepo_Expecter) Save(ctx any, t any) *TokenRepo_Save_Call {
	return &TokenRepo_Save_Call{Call: _e.mock.On("Save", ctx, t)}
}

func (_c *TokenRepo_Save_Call) Run(run func(ctx context.Context, t credentials.Token)) *TokenRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 credentials.Token
		if args[1] != nil {
			arg1 = args[1].(credentials.Token)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenRepo_Save_Call) Return(err error) *TokenRepo_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenRepo_Save_Call) RunAndReturn(run func(ctx context.Context, t credentials.Token) error) *TokenRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}

// TouchLastUsed provides a mock function for the type TokenRepo
func (_mock *TokenRepo) TouchLastUsed(ctx context.Context, id uuid.UUID, at time.Time) error {
	ret := _mock.Called(ctx, id, at)

	if len(ret) == 0 {
		panic("no return value specified for TouchLastUsed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, id, at)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenRepo_TouchLastUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TouchLastUsed'
type TokenRepo_TouchLastUsed_Call struct {
	*mock.Call
}

// TouchLastUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - at time.Time
func (_e *TokenRepo_Expecter) TouchLastUsed(ctx any, id any, at any) *TokenRepo_TouchLastUsed_Call {
	return &TokenRepo_TouchLastUsed_Call{Call: _e.mock.On("TouchLastUsed", ctx, id, at)}
}

func (_c *TokenRepo_TouchLastUsed_Call) Run(run func(ctx context.Context, id uuid.UUID, at time.Time)) *TokenRepo_TouchLastUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TokenRepo_TouchLastUsed_Call) Return(err error) *TokenRepo_TouchLastUsed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenRepo_TouchLastUsed_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, at time.Time) error) *TokenRepo_TouchLastUsed_Call {
	_c.Call.Return(run)
	return _c
}
