// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/elleqt/llm-proxy-backend/internal/app"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewUsageRepo creates a new instance of UsageRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsageRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsageRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &UsageRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// UsageRepo is an autogenerated mock type for the UsageRepo type
type UsageRepo struct {
	mock.Mock
}

type UsageRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *UsageRepo) EXPECT() *UsageRepo_Expecter {
	return &UsageRepo_Expecter{mock: &_m.Mock}
}

// AppendBatch provides a mock function for the type UsageRepo
func (_mock *UsageRepo) AppendBatch(ctx context.Context, events []app.UsageEvent) error {
	ret := _mock.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for AppendBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []app.UsageEvent) error); ok {
		r0 = returnFunc(ctx, events)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UsageRepo_AppendBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendBatch'
type UsageRepo_AppendBatch_Call struct {
	*mock.Call
}

// AppendBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - events []app.UsageEvent
func (_e *UsageRepo_Expecter) AppendBatch(ctx any, events any) *UsageRepo_AppendBatch_Call {
	return &UsageRepo_AppendBatch_Call{Call: _e.mock.On("AppendBatch", ctx, events)}
}

func (_c *UsageRepo_AppendBatch_Call) Run(run func(ctx context.Context, events []app.UsageEvent)) *UsageRepo_AppendBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []app.UsageEvent
		if args[1] != nil {
			arg1 = args[1].([]app.UsageEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UsageRepo_AppendBatch_Call) Return(err error) *UsageRepo_AppendBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UsageRepo_AppendBatch_Call) RunAndReturn(run func(ctx context.Context, events []app.UsageEvent) error) *UsageRepo_AppendBatch_Call {
	_c.Call.Return(run)
	return _c
}

// SeriesForUser provides a mock function for the type UsageRepo
func (_mock *UsageRepo) SeriesForUser(ctx context.Context, userID uuid.UUID, from time.Time, to time.Time) (app.UsageSeries, error) {
	ret := _mock.Called(ctx, userID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for SeriesForUser")
	}

	var r0 app.UsageSeries
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) (app.UsageSeries, error)); ok {
		return returnFunc(ctx, userID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) app.UsageSeries); ok {
		r0 = returnFunc(ctx, userID, from, to)
	} else {
		r0 = ret.Get(0).(app.UsageSeries)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsageRepo_SeriesForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SeriesForUser'
type UsageRepo_SeriesForUser_Call struct {
	*mock.Call
}

// SeriesForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *UsageRepo_Expecter) SeriesForUser(ctx any, userID any, from any, to any) *UsageRepo_SeriesForUser_Call {
	return &UsageRepo_SeriesForUser_Call{Call: _e.mock.On("SeriesForUser", ctx, userID, from, to)}
}

func (_c *UsageRepo_SeriesForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, from time.Time, to time.Time)) *UsageRepo_SeriesForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *UsageRepo_SeriesForUser_Call) Return(usageSeries app.UsageSeries, err error) *UsageRepo_SeriesForUser_Call {
	_c.Call.Return(usageSeries, err)
	return _c
}

func (_c *UsageRepo_SeriesForUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, from time.Time, to time.Time) (app.UsageSeries, error)) *UsageRepo_SeriesForUser_Call {
	_c.Call.Return(run)
	return _c
}
