// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/elleqt/llm-proxy-backend/internal/app"
	"github.com/elleqt/llm-proxy-backend/internal/domain/access"
	"github.com/elleqt/llm-proxy-backend/internal/domain/identity"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

type UserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepo) EXPECT() *UserRepo_Expecter {
	return &UserRepo_Expecter{mock: &_m.Mock}
}

// AdminExists provides a mock function for the type UserRepo
func (_mock *UserRepo) AdminExists(ctx context.Context) (bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AdminExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_AdminExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminExists'
type UserRepo_AdminExists_Call struct {
	*mock.Call
}

// AdminExists is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserRepo_Expecter) AdminExists(ctx any) *UserRepo_AdminExists_Call {
	return &UserRepo_AdminExists_Call{Call: _e.mock.On("AdminExists", ctx)}
}

func (_c *UserRepo_AdminExists_Call) Run(run func(ctx context.Context)) *UserRepo_AdminExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserRepo_AdminExists_Call) Return(b bool, err error) *UserRepo_AdminExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *UserRepo_AdminExists_Call) RunAndReturn(run func(ctx context.Context) (bool, error)) *UserRepo_AdminExists_Call {
	_c.Call.Return(run)
	return _c
}

// ByEmail provides a mock function for the type UserRepo
func (_mock *UserRepo) ByEmail(ctx context.Context, email string) (identity.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ByEmail")
	}

	var r0 identity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (identity.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) identity.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(identity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_ByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByEmail'
type UserRepo_ByEmail_Call struct {
	*mock.Call
}

// ByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepo_Expecter) ByEmail(ctx any, email any) *UserRepo_ByEmail_Call {
	return &UserRepo_ByEmail_Call{Call: _e.mock.On("ByEmail", ctx, email)}
}

func (_c *UserRepo_ByEmail_Call) Run(run func(ctx context.Context, email string)) *UserRepo_ByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_ByEmail_Call) Return(user identity.User, err error) *UserRepo_ByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepo_ByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (identity.User, error)) *UserRepo_ByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ByID provides a mock function for the type UserRepo
func (_mock *UserRepo) ByID(ctx context.Context, id uuid.UUID) (identity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 identity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (identity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) identity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(identity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type UserRepo_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *UserRepo_Expecter) ByID(ctx any, id any) *UserRepo_ByID_Call {
	return &UserRepo_ByID_Call{Call: _e.mock.On("ByID", ctx, id)}
}

func (_c *UserRepo_ByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *UserRepo_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_ByID_Call) Return(user identity.User, err error) *UserRepo_ByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepo_ByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (identity.User, error)) *UserRepo_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type UserRepo
func (_mock *UserRepo) Create(ctx context.Context, u identity.User) error {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, identity.User) error); ok {
		r0 = returnFunc(ctx, u)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - u identity.User
func (_e *UserRepo_Expecter) Create(ctx any, u any) *UserRepo_Create_Call {
	return &UserRepo_Create_Call{Call: _e.mock.On("Create", ctx, u)}
}

func (_c *UserRepo_Create_Call) Run(run func(ctx context.Context, u identity.User)) *UserRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 identity.User
		if args[1] != nil {
			arg1 = args[1].(identity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_Create_Call) Return(err error) *UserRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepo_Create_Call) RunAndReturn(run func(ctx context.Context, u identity.User) error) *UserRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAccount provides a mock function for the type UserRepo
func (_mock *UserRepo) CreateAccount(ctx context.Context, a app.NewAccount) error {
	ret := _mock.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.NewAccount) error); ok {
		r0 = returnFunc(ctx, a)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepo_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type UserRepo_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - a app.NewAccount
func (_e *UserRepo_Expecter) CreateAccount(ctx any, a any) *UserRepo_CreateAccount_Call {
	return &UserRepo_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, a)}
}

func (_c *UserRepo_CreateAccount_Call) Run(run func(ctx context.Context, a app.NewAccount)) *UserRepo_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.NewAccount
		if args[1] != nil {
			arg1 = args[1].(app.NewAccount)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_CreateAccount_Call) Return(err error) *UserRepo_CreateAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepo_CreateAccount_Call) RunAndReturn(run func(ctx context.Context, a app.NewAccount) error) *UserRepo_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// FillDisplayName provides a mock function for the type UserRepo
func (_mock *UserRepo) FillDisplayName(ctx context.Context, id uuid.UUID, name string) (bool, error) {
	ret := _mock.Called(ctx, id, name)

	if len(ret) == 0 {
		panic("no return value specified for FillDisplayName")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (bool, error)); ok {
		return returnFunc(ctx, id, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) bool); ok {
		r0 = returnFunc(ctx, id, name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, id, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_FillDisplayName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FillDisplayName'
type UserRepo_FillDisplayName_Call struct {
	*mock.Call
}

// FillDisplayName is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - name string
func (_e *UserRepo_Expecter) FillDisplayName(ctx any, id any, name any) *UserRepo_FillDisplayName_Call {
	return &UserRepo_FillDisplayName_Call{Call: _e.mock.On("FillDisplayName", ctx, id, name)}
}

func (_c *UserRepo_FillDisplayName_Call) Run(run func(ctx context.Context, id uuid.UUID, name string)) *UserRepo_FillDisplayName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepo_FillDisplayName_Call) Return(b bool, err error) *UserRepo_FillDisplayName_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *UserRepo_FillDisplayName_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, name string) (bool, error)) *UserRepo_FillDisplayName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type UserRepo
func (_mock *UserRepo) List(ctx context.Context) ([]app.UserView, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []app.UserView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]app.UserView, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []app.UserView); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]app.UserView)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type UserRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserRepo_Expecter) List(ctx any) *UserRepo_List_Call {
	return &UserRepo_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *UserRepo_List_Call) Run(run func(ctx context.Context)) *UserRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserRepo_List_Call) Return(userViews []app.UserView, err error) *UserRepo_List_Call {
	_c.Call.Return(userViews, err)
	return _c
}

func (_c *UserRepo_List_Call) RunAndReturn(run func(ctx context.Context) ([]app.UserView, error)) *UserRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// SaveIdentityState provides a mock function for the type UserRepo
func (_mock *UserRepo) SaveIdentityState(ctx context.Context, u identity.User) error {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for SaveIdentityState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, identity.User) error); ok {
		r0 = returnFunc(ctx, u)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepo_SaveIdentityState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveIdentityState'
type UserRepo_SaveIdentityState_Call struct {
	*mock.Call
}

// SaveIdentityState is a helper method to define mock.On call
//   - ctx context.Context
//   - u identity.User
func (_e *UserRepo_Expecter) SaveIdentityState(ctx any, u any) *UserRepo_SaveIdentityState_Call {
	return &UserRepo_SaveIdentityState_Call{Call: _e.mock.On("SaveIdentityState", ctx, u)}
}

func (_c *UserRepo_SaveIdentityState_Call) Run(run func(ctx context.Context, u identity.User)) *UserRepo_SaveIdentityState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 identity.User
		if args[1] != nil {
			arg1 = args[1].(identity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_SaveIdentityState_Call) Return(err error) *UserRepo_SaveIdentityState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepo_SaveIdentityState_Call) RunAndReturn(run func(ctx context.Context, u identity.User) error) *UserRepo_SaveIdentityState_Call {
	_c.Call.Return(run)
	return _c
}

// SetMustChangePassword provides a mock function for the type UserRepo
func (_mock *UserRepo) SetMustChangePassword(ctx context.Context, id uuid.UUID, must bool) error {
	ret := _mock.Called(ctx, id, must)

	if len(ret) == 0 {
		panic("no return value specified for SetMustChangePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, id, must)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepo_SetMustChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMustChangePassword'
type UserRepo_SetMustChangePassword_Call struct {
	*mock.Call
}

// SetMustChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - must bool
func (_e *UserRepo_Expecter) SetMustChangePassword(ctx any, id any, must any) *UserRepo_SetMustChangePassword_Call {
	return &UserRepo_SetMustChangePassword_Call{Call: _e.mock.On("SetMustChangePassword", ctx, id, must)}
}

func (_c *UserRepo_SetMustChangePassword_Call) Run(run func(ctx context.Context, id uuid.UUID, must bool)) *UserRepo_SetMustChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepo_SetMustChangePassword_Call) Return(err error) *UserRepo_SetMustChangePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepo_SetMustChangePassword_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, must bool) error) *UserRepo_SetMustChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// TouchLastSeen provides a mock function for the type UserRepo
func (_mock *UserRepo) TouchLastSeen(ctx context.Context, id uuid.UUID, at time.Time) error {
	ret := _mock.Called(ctx, id, at)

	if len(ret) == 0 {
		panic("no return value specified for TouchLastSeen")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, id, at)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepo_TouchLastSeen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TouchLastSeen'
type UserRepo_TouchLastSeen_Call struct {
	*mock.Call
}

// TouchLastSeen is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - at time.Time
func (_e *UserRepo_Expecter) TouchLastSeen(ctx any, id any, at any) *UserRepo_TouchLastSeen_Call {
	return &UserRepo_TouchLastSeen_Call{Call: _e.mock.On("TouchLastSeen", ctx, id, at)}
}

func (_c *UserRepo_TouchLastSeen_Call) Run(run func(ctx context.Context, id uuid.UUID, at time.Time)) *UserRepo_TouchLastSeen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepo_TouchLastSeen_Call) Return(err error) *UserRepo_TouchLastSeen_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepo_TouchLastSeen_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, at time.Time) error) *UserRepo_TouchLastSeen_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAdminState provides a mock function for the type UserRepo
func (_mock *UserRepo) UpdateAdminState(ctx context.Context, id uuid.UUID, ch app.AdminChange) error {
	ret := _mock.Called(ctx, id, ch)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAdminState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, app.AdminChange) error); ok {
		r0 = returnFunc(ctx, id, ch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepo_UpdateAdminState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAdminState'
type UserRepo_UpdateAdminState_Call struct {
	*mock.Call
}

// UpdateAdminState is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - ch app.AdminChange
func (_e *UserRepo_Expecter) UpdateAdminState(ctx any, id any, ch any) *UserRepo_UpdateAdminState_Call {
	return &UserRepo_UpdateAdminState_Call{Call: _e.mock.On("UpdateAdminState", ctx, id, ch)}
}

func (_c *UserRepo_UpdateAdminState_Call) Run(run func(ctx context.Context, id uuid.UUID, ch app.AdminChange)) *UserRepo_UpdateAdminState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 app.AdminChange
		if args[2] != nil {
			arg2 = args[2].(app.AdminChange)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepo_UpdateAdminState_Call) Return(err error) *UserRepo_UpdateAdminState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepo_UpdateAdminState_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, ch app.AdminChange) error) *UserRepo_UpdateAdminState_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePolicy provides a mock function for the type UserRepo
func (_mock *UserRepo) UpdatePolicy(ctx context.Context, id uuid.UUID, p access.Policy) error {
	ret := _mock.Called(ctx, id, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, access.Policy) error); ok {
		r0 = returnFunc(ctx, id, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepo_UpdatePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePolicy'
type UserRepo_UpdatePolicy_Call struct {
	*mock.Call
}

// UpdatePolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - p access.Policy
func (_e *UserRepo_Expecter) UpdatePolicy(ctx any, id any, p any) *UserRepo_UpdatePolicy_Call {
	return &UserRepo_UpdatePolicy_Call{Call: _e.mock.On("UpdatePolicy", ctx, id, p)}
}

func (_c *UserRepo_UpdatePolicy_Call) Run(run func(ctx context.Context, id uuid.UUID, p access.Policy)) *UserRepo_UpdatePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 access.Policy
		if args[2] != nil {
			arg2 = args[2].(access.Policy)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepo_UpdatePolicy_Call) Return(err error) *UserRepo_UpdatePolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepo_UpdatePolicy_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, p access.Policy) error) *UserRepo_UpdatePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// View provides a mock function for the type UserRepo
func (_mock *UserRepo) View(ctx context.Context, id uuid.UUID) (app.UserView, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for View")
	}

	var r0 app.UserView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (app.UserView, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) app.UserView); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(app.UserView)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_View_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'View'
type UserRepo_View_Call struct {
	*mock.Call
}

// View is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *UserRepo_Expecter) View(ctx any, id any) *UserRepo_View_Call {
	return &UserRepo_View_Call{Call: _e.mock.On("View", ctx, id)}
}

func (_c *UserRepo_View_Call) Run(run func(ctx context.Context, id uuid.UUID)) *UserRepo_View_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_View_Call) Return(userView app.UserView, err error) *UserRepo_View_Call {
	_c.Call.Return(userView, err)
	return _c
}

func (_c *UserRepo_View_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (app.UserView, error)) *UserRepo_View_Call {
	_c.Call.Return(run)
	return _c
}
