// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/elleqt/llm-proxy-backend/internal/app"
	mock "github.com/stretchr/testify/mock"
)

// NewVendorAccounts creates a new instance of VendorAccounts. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVendorAccounts(t interface {
	mock.TestingT
	Cleanup(func())
}) *VendorAccounts {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &VendorAccounts{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// VendorAccounts is an autogenerated mock type for the VendorAccounts type
type VendorAccounts struct {
	mock.Mock
}

type VendorAccounts_Expecter struct {
	mock *mock.Mock
}

func (_m *VendorAccounts) EXPECT() *VendorAccounts_Expecter {
	return &VendorAccounts_Expecter{mock: &_m.Mock}
}

// Accounts provides a mock function for the type VendorAccounts
func (_mock *VendorAccounts) Accounts() []app.VendorAccount {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Accounts")
	}

	var r0 []app.VendorAccount
	if returnFunc, ok := ret.Get(0).(func() []app.VendorAccount); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]app.VendorAccount)
		}
	}
	return r0
}

// VendorAccounts_Accounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accounts'
type VendorAccounts_Accounts_Call struct {
	*mock.Call
}

// Accounts is a helper method to define mock.On call
func (_e *VendorAccounts_Expecter) Accounts() *VendorAccounts_Accounts_Call {
	return &VendorAccounts_Accounts_Call{Call: _e.mock.On("Accounts")}
}

func (_c *VendorAccounts_Accounts_Call) Run(run func()) *VendorAccounts_Accounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VendorAccounts_Accounts_Call) Return(vendorAccounts []app.VendorAccount) *VendorAccounts_Accounts_Call {
	_c.Call.Return(vendorAccounts)
	return _c
}

func (_c *VendorAccounts_Accounts_Call) RunAndReturn(run func() []app.VendorAccount) *VendorAccounts_Accounts_Call {
	_c.Call.Return(run)
	return _c
}

// AddCompatProvider provides a mock function for the type VendorAccounts
func (_mock *VendorAccounts) AddCompatProvider(ctx context.Context, p app.CompatProvider) (app.VendorAccount, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for AddCompatProvider")
	}

	var r0 app.VendorAccount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.CompatProvider) (app.VendorAccount, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.CompatProvider) app.VendorAccount); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Get(0).(app.VendorAccount)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.CompatProvider) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VendorAccounts_AddCompatProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCompatProvider'
type VendorAccounts_AddCompatProvider_Call struct {
	*mock.Call
}

// AddCompatProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - p app.CompatProvider
func (_e *VendorAccounts_Expecter) AddCompatProvider(ctx any, p any) *VendorAccounts_AddCompatProvider_Call {
	return &VendorAccounts_AddCompatProvider_Call{Call: _e.mock.On("AddCompatProvider", ctx, p)}
}

func (_c *VendorAccounts_AddCompatProvider_Call) Run(run func(ctx context.Context, p app.CompatProvider)) *VendorAccounts_AddCompatProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.CompatProvider
		if args[1] != nil {
			arg1 = args[1].(app.CompatProvider)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VendorAccounts_AddCompatProvider_Call) Return(vendorAccount app.VendorAccount, err error) *VendorAccounts_AddCompatProvider_Call {
	_c.Call.Return(vendorAccount, err)
	return _c
}

func (_c *VendorAccounts_AddCompatProvider_Call) RunAndReturn(run func(ctx context.Context, p app.CompatProvider) (app.VendorAccount, error)) *VendorAccounts_AddCompatProvider_Call {
	_c.Call.Return(run)
	return _c
}

// DiscoverModels provides a mock function for the type VendorAccounts
func (_mock *VendorAccounts) DiscoverModels(ctx context.Context, baseURL string, apiKey string, accountID string, proxy *app.ProxyChoice) ([]string, error) {
	ret := _mock.Called(ctx, baseURL, apiKey, accountID, proxy)

	if len(ret) == 0 {
		panic("no return value specified for DiscoverModels")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *app.ProxyChoice) ([]string, error)); ok {
		return returnFunc(ctx, baseURL, apiKey, accountID, proxy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *app.ProxyChoice) []string); ok {
		r0 = returnFunc(ctx, baseURL, apiKey, accountID, proxy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, *app.ProxyChoice) error); ok {
		r1 = returnFunc(ctx, baseURL, apiKey, accountID, proxy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VendorAccounts_DiscoverModels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoverModels'
type VendorAccounts_DiscoverModels_Call struct {
	*mock.Call
}

// DiscoverModels is a helper method to define mock.On call
//   - ctx context.Context
//   - baseURL string
//   - apiKey string
//   - accountID string
//   - proxy *app.ProxyChoice
func (_e *VendorAccounts_Expecter) DiscoverModels(ctx any, baseURL any, apiKey any, accountID any, proxy any) *VendorAccounts_DiscoverModels_Call {
	return &VendorAccounts_DiscoverModels_Call{Call: _e.mock.On("DiscoverModels", ctx, baseURL, apiKey, accountID, proxy)}
}

func (_c *VendorAccounts_DiscoverModels_Call) Run(run func(ctx context.Context, baseURL string, apiKey string, accountID string, proxy *app.ProxyChoice)) *VendorAccounts_DiscoverModels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *app.ProxyChoice
		if args[4] != nil {
			arg4 = args[4].(*app.ProxyChoice)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *VendorAccounts_DiscoverModels_Call) Return(strings []string, err error) *VendorAccounts_DiscoverModels_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *VendorAccounts_DiscoverModels_Call) RunAndReturn(run func(ctx context.Context, baseURL string, apiKey string, accountID string, proxy *app.ProxyChoice) ([]string, error)) *VendorAccounts_DiscoverModels_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAccount provides a mock function for the type VendorAccounts
func (_mock *VendorAccounts) RemoveAccount(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VendorAccounts_RemoveAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAccount'
type VendorAccounts_RemoveAccount_Call struct {
	*mock.Call
}

// RemoveAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *VendorAccounts_Expecter) RemoveAccount(ctx any, id any) *VendorAccounts_RemoveAccount_Call {
	return &VendorAccounts_RemoveAccount_Call{Call: _e.mock.On("RemoveAccount", ctx, id)}
}

func (_c *VendorAccounts_RemoveAccount_Call) Run(run func(ctx context.Context, id string)) *VendorAccounts_RemoveAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VendorAccounts_RemoveAccount_Call) Return(err error) *VendorAccounts_RemoveAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VendorAccounts_RemoveAccount_Call) RunAndReturn(run func(ctx context.Context, id string) error) *VendorAccounts_RemoveAccount_Call {
	_c.Call.Return(run)
	return _c
}

// SetAccountDisabled provides a mock function for the type VendorAccounts
func (_mock *VendorAccounts) SetAccountDisabled(ctx context.Context, id string, disabled bool) error {
	ret := _mock.Called(ctx, id, disabled)

	if len(ret) == 0 {
		panic("no return value specified for SetAccountDisabled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, id, disabled)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VendorAccounts_SetAccountDisabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAccountDisabled'
type VendorAccounts_SetAccountDisabled_Call struct {
	*mock.Call
}

// SetAccountDisabled is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - disabled bool
func (_e *VendorAccounts_Expecter) SetAccountDisabled(ctx any, id any, disabled any) *VendorAccounts_SetAccountDisabled_Call {
	return &VendorAccounts_SetAccountDisabled_Call{Call: _e.mock.On("SetAccountDisabled", ctx, id, disabled)}
}

func (_c *VendorAccounts_SetAccountDisabled_Call) Run(run func(ctx context.Context, id string, disabled bool)) *VendorAccounts_SetAccountDisabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *VendorAccounts_SetAccountDisabled_Call) Return(err error) *VendorAccounts_SetAccountDisabled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VendorAccounts_SetAccountDisabled_Call) RunAndReturn(run func(ctx context.Context, id string, disabled bool) error) *VendorAccounts_SetAccountDisabled_Call {
	_c.Call.Return(run)
	return _c
}

// SetAccountProxy provides a mock function for the type VendorAccounts
func (_mock *VendorAccounts) SetAccountProxy(ctx context.Context, id string, p app.ProxyChoice) error {
	ret := _mock.Called(ctx, id, p)

	if len(ret) == 0 {
		panic("no return value specified for SetAccountProxy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, app.ProxyChoice) error); ok {
		r0 = returnFunc(ctx, id, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VendorAccounts_SetAccountProxy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAccountProxy'
type VendorAccounts_SetAccountProxy_Call struct {
	*mock.Call
}

// SetAccountProxy is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - p app.ProxyChoice
func (_e *VendorAccounts_Expecter) SetAccountProxy(ctx any, id any, p any) *VendorAccounts_SetAccountProxy_Call {
	return &VendorAccounts_SetAccountProxy_Call{Call: _e.mock.On("SetAccountProxy", ctx, id, p)}
}

func (_c *VendorAccounts_SetAccountProxy_Call) Run(run func(ctx context.Context, id string, p app.ProxyChoice)) *VendorAccounts_SetAccountProxy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 app.ProxyChoice
		if args[2] != nil {
			arg2 = args[2].(app.ProxyChoice)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *VendorAccounts_SetAccountProxy_Call) Return(err error) *VendorAccounts_SetAccountProxy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VendorAccounts_SetAccountProxy_Call) RunAndReturn(run func(ctx context.Context, id string, p app.ProxyChoice) error) *VendorAccounts_SetAccountProxy_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCompatProvider provides a mock function for the type VendorAccounts
func (_mock *VendorAccounts) UpdateCompatProvider(ctx context.Context, id string, u app.CompatProviderUpdate) (app.VendorAccount, error) {
	ret := _mock.Called(ctx, id, u)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCompatProvider")
	}

	var r0 app.VendorAccount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, app.CompatProviderUpdate) (app.VendorAccount, error)); ok {
		return returnFunc(ctx, id, u)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, app.CompatProviderUpdate) app.VendorAccount); ok {
		r0 = returnFunc(ctx, id, u)
	} else {
		r0 = ret.Get(0).(app.VendorAccount)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, app.CompatProviderUpdate) error); ok {
		r1 = returnFunc(ctx, id, u)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VendorAccounts_UpdateCompatProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCompatProvider'
type VendorAccounts_UpdateCompatProvider_Call struct {
	*mock.Call
}

// UpdateCompatProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - u app.CompatProviderUpdate
func (_e *VendorAccounts_Expecter) UpdateCompatProvider(ctx any, id any, u any) *VendorAccounts_UpdateCompatProvider_Call {
	return &VendorAccounts_UpdateCompatProvider_Call{Call: _e.mock.On("UpdateCompatProvider", ctx, id, u)}
}

func (_c *VendorAccounts_UpdateCompatProvider_Call) Run(run func(ctx context.Context, id string, u app.CompatProviderUpdate)) *VendorAccounts_UpdateCompatProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 app.CompatProviderUpdate
		if args[2] != nil {
			arg2 = args[2].(app.CompatProviderUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *VendorAccounts_UpdateCompatProvider_Call) Return(vendorAccount app.VendorAccount, err error) *VendorAccounts_UpdateCompatProvider_Call {
	_c.Call.Return(vendorAccount, err)
	return _c
}

func (_c *VendorAccounts_UpdateCompatProvider_Call) RunAndReturn(run func(ctx context.Context, id string, u app.CompatProviderUpdate) (app.VendorAccount, error)) *VendorAccounts_UpdateCompatProvider_Call {
	_c.Call.Return(run)
	return _c
}
