// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/elleqt/llm-proxy-backend/internal/app"
	mock "github.com/stretchr/testify/mock"
)

// NewVendorQuota creates a new instance of VendorQuota. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVendorQuota(t interface {
	mock.TestingT
	Cleanup(func())
}) *VendorQuota {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &VendorQuota{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// VendorQuota is an autogenerated mock type for the VendorQuota type
type VendorQuota struct {
	mock.Mock
}

type VendorQuota_Expecter struct {
	mock *mock.Mock
}

func (_m *VendorQuota) EXPECT() *VendorQuota_Expecter {
	return &VendorQuota_Expecter{mock: &_m.Mock}
}

// ForgetAccount provides a mock function for the type VendorQuota
func (_mock *VendorQuota) ForgetAccount(account string) {
	_mock.Called(account)
	return
}

// VendorQuota_ForgetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForgetAccount'
type VendorQuota_ForgetAccount_Call struct {
	*mock.Call
}

// ForgetAccount is a helper method to define mock.On call
//   - account string
func (_e *VendorQuota_Expecter) ForgetAccount(account any) *VendorQuota_ForgetAccount_Call {
	return &VendorQuota_ForgetAccount_Call{Call: _e.mock.On("ForgetAccount", account)}
}

func (_c *VendorQuota_ForgetAccount_Call) Run(run func(account string)) *VendorQuota_ForgetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *VendorQuota_ForgetAccount_Call) Return() *VendorQuota_ForgetAccount_Call {
	_c.Call.Return()
	return _c
}

func (_c *VendorQuota_ForgetAccount_Call) RunAndReturn(run func(account string)) *VendorQuota_ForgetAccount_Call {
	_c.Run(run)
	return _c
}

// QuotaSignals provides a mock function for the type VendorQuota
func (_mock *VendorQuota) QuotaSignals() []app.QuotaSignal {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for QuotaSignals")
	}

	var r0 []app.QuotaSignal
	if returnFunc, ok := ret.Get(0).(func() []app.QuotaSignal); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]app.QuotaSignal)
		}
	}
	return r0
}

// VendorQuota_QuotaSignals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QuotaSignals'
type VendorQuota_QuotaSignals_Call struct {
	*mock.Call
}

// QuotaSignals is a helper method to define mock.On call
func (_e *VendorQuota_Expecter) QuotaSignals() *VendorQuota_QuotaSignals_Call {
	return &VendorQuota_QuotaSignals_Call{Call: _e.mock.On("QuotaSignals")}
}

func (_c *VendorQuota_QuotaSignals_Call) Run(run func()) *VendorQuota_QuotaSignals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VendorQuota_QuotaSignals_Call) Return(quotaSignals []app.QuotaSignal) *VendorQuota_QuotaSignals_Call {
	_c.Call.Return(quotaSignals)
	return _c
}

func (_c *VendorQuota_QuotaSignals_Call) RunAndReturn(run func() []app.QuotaSignal) *VendorQuota_QuotaSignals_Call {
	_c.Call.Return(run)
	return _c
}
