// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/elleqt/llm-proxy-backend/internal/app"
	mock "github.com/stretchr/testify/mock"
)

// NewVendorLogins creates a new instance of VendorLogins. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVendorLogins(t interface {
	mock.TestingT
	Cleanup(func())
}) *VendorLogins {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &VendorLogins{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// VendorLogins is an autogenerated mock type for the VendorLogins type
type VendorLogins struct {
	mock.Mock
}

type VendorLogins_Expecter struct {
	mock *mock.Mock
}

func (_m *VendorLogins) EXPECT() *VendorLogins_Expecter {
	return &VendorLogins_Expecter{mock: &_m.Mock}
}

// CompleteLogin provides a mock function for the type VendorLogins
func (_mock *VendorLogins) CompleteLogin(ctx context.Context, sessionID string, callbackURL string) (app.VendorAccount, error) {
	ret := _mock.Called(ctx, sessionID, callbackURL)

	if len(ret) == 0 {
		panic("no return value specified for CompleteLogin")
	}

	var r0 app.VendorAccount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (app.VendorAccount, error)); ok {
		return returnFunc(ctx, sessionID, callbackURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) app.VendorAccount); ok {
		r0 = returnFunc(ctx, sessionID, callbackURL)
	} else {
		r0 = ret.Get(0).(app.VendorAccount)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, sessionID, callbackURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VendorLogins_CompleteLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteLogin'
type VendorLogins_CompleteLogin_Call struct {
	*mock.Call
}

// CompleteLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - callbackURL string
func (_e *VendorLogins_Expecter) CompleteLogin(ctx any, sessionID any, callbackURL any) *VendorLogins_CompleteLogin_Call {
	return &VendorLogins_CompleteLogin_Call{Call: _e.mock.On("CompleteLogin", ctx, sessionID, callbackURL)}
}

func (_c *VendorLogins_CompleteLogin_Call) Run(run func(ctx context.Context, sessionID string, callbackURL string)) *VendorLogins_CompleteLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *VendorLogins_CompleteLogin_Call) Return(vendorAccount app.VendorAccount, err error) *VendorLogins_CompleteLogin_Call {
	_c.Call.Return(vendorAccount, err)
	return _c
}

func (_c *VendorLogins_CompleteLogin_Call) RunAndReturn(run func(ctx context.Context, sessionID string, callbackURL string) (app.VendorAccount, error)) *VendorLogins_CompleteLogin_Call {
	_c.Call.Return(run)
	return _c
}

// StartLogin provides a mock function for the type VendorLogins
func (_mock *VendorLogins) StartLogin(ctx context.Context, provider string) (app.VendorLogin, error) {
	ret := _mock.Called(ctx, provider)

	if len(ret) == 0 {
		panic("no return value specified for StartLogin")
	}

	var r0 app.VendorLogin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (app.VendorLogin, error)); ok {
		return returnFunc(ctx, provider)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) app.VendorLogin); ok {
		r0 = returnFunc(ctx, provider)
	} else {
		r0 = ret.Get(0).(app.VendorLogin)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, provider)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VendorLogins_StartLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartLogin'
type VendorLogins_StartLogin_Call struct {
	*mock.Call
}

// StartLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
func (_e *VendorLogins_Expecter) StartLogin(ctx any, provider any) *VendorLogins_StartLogin_Call {
	return &VendorLogins_StartLogin_Call{Call: _e.mock.On("StartLogin", ctx, provider)}
}

func (_c *VendorLogins_StartLogin_Call) Run(run func(ctx context.Context, provider string)) *VendorLogins_StartLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VendorLogins_StartLogin_Call) Return(vendorLogin app.VendorLogin, err error) *VendorLogins_StartLogin_Call {
	_c.Call.Return(vendorLogin, err)
	return _c
}

func (_c *VendorLogins_StartLogin_Call) RunAndReturn(run func(ctx context.Context, provider string) (app.VendorLogin, error)) *VendorLogins_StartLogin_Call {
	_c.Call.Return(run)
	return _c
}
