// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/elleqt/llm-proxy-backend/internal/app"
	mock "github.com/stretchr/testify/mock"
)

// NewVendorCredentialRepo creates a new instance of VendorCredentialRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVendorCredentialRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *VendorCredentialRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &VendorCredentialRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// VendorCredentialRepo is an autogenerated mock type for the VendorCredentialRepo type
type VendorCredentialRepo struct {
	mock.Mock
}

type VendorCredentialRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *VendorCredentialRepo) EXPECT() *VendorCredentialRepo_Expecter {
	return &VendorCredentialRepo_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type VendorCredentialRepo
func (_mock *VendorCredentialRepo) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VendorCredentialRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type VendorCredentialRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *VendorCredentialRepo_Expecter) Delete(ctx any, id any) *VendorCredentialRepo_Delete_Call {
	return &VendorCredentialRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *VendorCredentialRepo_Delete_Call) Run(run func(ctx context.Context, id string)) *VendorCredentialRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VendorCredentialRepo_Delete_Call) Return(err error) *VendorCredentialRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VendorCredentialRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *VendorCredentialRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Import provides a mock function for the type VendorCredentialRepo
func (_mock *VendorCredentialRepo) Import(ctx context.Context, rows []app.VendorCredential) (bool, error) {
	ret := _mock.Called(ctx, rows)

	if len(ret) == 0 {
		panic("no return value specified for Import")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []app.VendorCredential) (bool, error)); ok {
		return returnFunc(ctx, rows)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []app.VendorCredential) bool); ok {
		r0 = returnFunc(ctx, rows)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []app.VendorCredential) error); ok {
		r1 = returnFunc(ctx, rows)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VendorCredentialRepo_Import_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Import'
type VendorCredentialRepo_Import_Call struct {
	*mock.Call
}

// Import is a helper method to define mock.On call
//   - ctx context.Context
//   - rows []app.VendorCredential
func (_e *VendorCredentialRepo_Expecter) Import(ctx any, rows any) *VendorCredentialRepo_Import_Call {
	return &VendorCredentialRepo_Import_Call{Call: _e.mock.On("Import", ctx, rows)}
}

func (_c *VendorCredentialRepo_Import_Call) Run(run func(ctx context.Context, rows []app.VendorCredential)) *VendorCredentialRepo_Import_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []app.VendorCredential
		if args[1] != nil {
			arg1 = args[1].([]app.VendorCredential)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VendorCredentialRepo_Import_Call) Return(b bool, err error) *VendorCredentialRepo_Import_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *VendorCredentialRepo_Import_Call) RunAndReturn(run func(ctx context.Context, rows []app.VendorCredential) (bool, error)) *VendorCredentialRepo_Import_Call {
	_c.Call.Return(run)
	return _c
}

// ImportDone provides a mock function for the type VendorCredentialRepo
func (_mock *VendorCredentialRepo) ImportDone(ctx context.Context) (bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ImportDone")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VendorCredentialRepo_ImportDone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportDone'
type VendorCredentialRepo_ImportDone_Call struct {
	*mock.Call
}

// ImportDone is a helper method to define mock.On call
//   - ctx context.Context
func (_e *VendorCredentialRepo_Expecter) ImportDone(ctx any) *VendorCredentialRepo_ImportDone_Call {
	return &VendorCredentialRepo_ImportDone_Call{Call: _e.mock.On("ImportDone", ctx)}
}

func (_c *VendorCredentialRepo_ImportDone_Call) Run(run func(ctx context.Context)) *VendorCredentialRepo_ImportDone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *VendorCredentialRepo_ImportDone_Call) Return(b bool, err error) *VendorCredentialRepo_ImportDone_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *VendorCredentialRepo_ImportDone_Call) RunAndReturn(run func(ctx context.Context) (bool, error)) *VendorCredentialRepo_ImportDone_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type VendorCredentialRepo
func (_mock *VendorCredentialRepo) List(ctx context.Context) ([]app.VendorCredential, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []app.VendorCredential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]app.VendorCredential, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []app.VendorCredential); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]app.VendorCredential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VendorCredentialRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type VendorCredentialRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *VendorCredentialRepo_Expecter) List(ctx any) *VendorCredentialRepo_List_Call {
	return &VendorCredentialRepo_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *VendorCredentialRepo_List_Call) Run(run func(ctx context.Context)) *VendorCredentialRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *VendorCredentialRepo_List_Call) Return(vendorCredentials []app.VendorCredential, err error) *VendorCredentialRepo_List_Call {
	_c.Call.Return(vendorCredentials, err)
	return _c
}

func (_c *VendorCredentialRepo_List_Call) RunAndReturn(run func(ctx context.Context) ([]app.VendorCredential, error)) *VendorCredentialRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type VendorCredentialRepo
func (_mock *VendorCredentialRepo) Update(ctx context.Context, c app.VendorCredential) error {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.VendorCredential) error); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VendorCredentialRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type VendorCredentialRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - c app.VendorCredential
func (_e *VendorCredentialRepo_Expecter) Update(ctx any, c any) *VendorCredentialRepo_Update_Call {
	return &VendorCredentialRepo_Update_Call{Call: _e.mock.On("Update", ctx, c)}
}

func (_c *VendorCredentialRepo_Update_Call) Run(run func(ctx context.Context, c app.VendorCredential)) *VendorCredentialRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.VendorCredential
		if args[1] != nil {
			arg1 = args[1].(app.VendorCredential)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VendorCredentialRepo_Update_Call) Return(err error) *VendorCredentialRepo_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VendorCredentialRepo_Update_Call) RunAndReturn(run func(ctx context.Context, c app.VendorCredential) error) *VendorCredentialRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type VendorCredentialRepo
func (_mock *VendorCredentialRepo) Upsert(ctx context.Context, c app.VendorCredential) error {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.VendorCredential) error); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VendorCredentialRepo_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type VendorCredentialRepo_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - c app.VendorCredential
func (_e *VendorCredentialRepo_Expecter) Upsert(ctx any, c any) *VendorCredentialRepo_Upsert_Call {
	return &VendorCredentialRepo_Upsert_Call{Call: _e.mock.On("Upsert", ctx, c)}
}

func (_c *VendorCredentialRepo_Upsert_Call) Run(run func(ctx context.Context, c app.VendorCredential)) *VendorCredentialRepo_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.VendorCredential
		if args[1] != nil {
			arg1 = args[1].(app.VendorCredential)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VendorCredentialRepo_Upsert_Call) Return(err error) *VendorCredentialRepo_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VendorCredentialRepo_Upsert_Call) RunAndReturn(run func(ctx context.Context, c app.VendorCredential) error) *VendorCredentialRepo_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
