// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/elleqt/llm-proxy-backend/internal/app"
	mock "github.com/stretchr/testify/mock"
)

// NewVendorAccounts creates a new instance of VendorAccounts. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVendorAccounts(t interface {
	mock.TestingT
	Cleanup(func())
}) *VendorAccounts {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &VendorAccounts{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// VendorAccounts is an autogenerated mock type for the VendorAccounts type
type VendorAccounts struct {
	mock.Mock
}

type VendorAccounts_Expecter struct {
	mock *mock.Mock
}

func (_m *VendorAccounts) EXPECT() *VendorAccounts_Expecter {
	return &VendorAccounts_Expecter{mock: &_m.Mock}
}

// Accounts provides a mock function for the type VendorAccounts
func (_mock *VendorAccounts) Accounts() []app.VendorAccount {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Accounts")
	}

	var r0 []app.VendorAccount
	if returnFunc, ok := ret.Get(0).(func() []app.VendorAccount); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]app.VendorAccount)
		}
	}
	return r0
}

// VendorAccounts_Accounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accounts'
type VendorAccounts_Accounts_Call struct {
	*mock.Call
}

// Accounts is a helper method to define mock.On call
func (_e *VendorAccounts_Expecter) Accounts() *VendorAccounts_Accounts_Call {
	return &VendorAccounts_Accounts_Call{Call: _e.mock.On("Accounts")}
}

func (_c *VendorAccounts_Accounts_Call) Run(run func()) *VendorAccounts_Accounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VendorAccounts_Accounts_Call) Return(vendorAccounts []app.VendorAccount) *VendorAccounts_Accounts_Call {
	_c.Call.Return(vendorAccounts)
	return _c
}

func (_c *VendorAccounts_Accounts_Call) RunAndReturn(run func() []app.VendorAccount) *VendorAccounts_Accounts_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAccount provides a mock function for the type VendorAccounts
func (_mock *VendorAccounts) RemoveAccount(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VendorAccounts_RemoveAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAccount'
type VendorAccounts_RemoveAccount_Call struct {
	*mock.Call
}

// RemoveAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *VendorAccounts_Expecter) RemoveAccount(ctx any, id any) *VendorAccounts_RemoveAccount_Call {
	return &VendorAccounts_RemoveAccount_Call{Call: _e.mock.On("RemoveAccount", ctx, id)}
}

func (_c *VendorAccounts_RemoveAccount_Call) Run(run func(ctx context.Context, id string)) *VendorAccounts_RemoveAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VendorAccounts_RemoveAccount_Call) Return(err error) *VendorAccounts_RemoveAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VendorAccounts_RemoveAccount_Call) RunAndReturn(run func(ctx context.Context, id string) error) *VendorAccounts_RemoveAccount_Call {
	_c.Call.Return(run)
	return _c
}

// SetAccountDisabled provides a mock function for the type VendorAccounts
func (_mock *VendorAccounts) SetAccountDisabled(ctx context.Context, id string, disabled bool) error {
	ret := _mock.Called(ctx, id, disabled)

	if len(ret) == 0 {
		panic("no return value specified for SetAccountDisabled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, id, disabled)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VendorAccounts_SetAccountDisabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAccountDisabled'
type VendorAccounts_SetAccountDisabled_Call struct {
	*mock.Call
}

// SetAccountDisabled is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - disabled bool
func (_e *VendorAccounts_Expecter) SetAccountDisabled(ctx any, id any, disabled any) *VendorAccounts_SetAccountDisabled_Call {
	return &VendorAccounts_SetAccountDisabled_Call{Call: _e.mock.On("SetAccountDisabled", ctx, id, disabled)}
}

func (_c *VendorAccounts_SetAccountDisabled_Call) Run(run func(ctx context.Context, id string, disabled bool)) *VendorAccounts_SetAccountDisabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *VendorAccounts_SetAccountDisabled_Call) Return(err error) *VendorAccounts_SetAccountDisabled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VendorAccounts_SetAccountDisabled_Call) RunAndReturn(run func(ctx context.Context, id string, disabled bool) error) *VendorAccounts_SetAccountDisabled_Call {
	_c.Call.Return(run)
	return _c
}
